In [2]:
import numpy as np
import pandas as pd
import time
import datetime
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
from sklearn.model_selection import KFold, cross_val_score, train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_selection import SelectKBest, chi2, SelectPercentile
from scipy import sparse
from sklearn.model_selection  import StratifiedKFold
from sklearn.metrics import roc_auc_score, log_loss
import lightgbm as lgb
import gc
import os
import warnings
warnings.filterwarnings("ignore")

In [7]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [8]:
train = pd.read_table('./data/round1_iflyad_train.txt')
train.drop_duplicates(keep='first',inplace = False)
train.head()

,instance_id,time,city,province,user_tags,carrier,devtype,make,model,nnt,os,osv,os_name,adid,advert_id,orderid,advert_industry_inner,campaign_id,creative_id,creative_tp_dnf,app_cate_id,f_channel,app_id,inner_slot_id,creative_type,creative_width,creative_height,creative_is_jump,creative_is_download,creative_is_js,creative_is_voicead,creative_has_deeplink,app_paid,advert_name,click
0,86294719979897807,2190219034,137103102105100,137103102100100,NaN,1,2,HUAWEI,HUAWEI-CAZ-AL10,1,2,7.0.0,android,1560128,230000063,3010798,102400_102401,1000023,2338420,8390267734059046014,107.0,NaN,2089229.0,xf_275C061483984E075832A4373BDDF27B,8,1280,720,True,False,False,False,False,False,B4734117F35EE97F,0
1,2699289844928136052,2190221070,137105101100100,137105101100100,"2100191,2100078,3001825,,3001781,3001791,30017...",3,2,Xiaomi,Redmi Note 4,1,2,6.0,android,1488859,230000063,2311397,102400_102401,1000023,2310417,8390208550469153745,108.0,NaN,2070079.0,xf_D84DAB691E2E08C5B80D2FF5135F886E,8,960,640,True,False,False,False,False,False,B4734117F35EE97F,0
2,3117527168445845752,2190219793,137103104111100,137103104100100,NaN,3,2,OPPO,OPPO+R11s,1,2,7.1.1,android,1537089,230000065,3008491,101700_101704,1000021,2337017,8390430283595430291,100.0,NaN,2089397.0,xf_7F9FF3BEA11FE5B3AE6332EFBBD59496,8,960,640,True,False,False,False,False,False,E257895F74792E81,0
3,3398484891050993371,2190221704,137103102113100,137103102100100,"2100098,gd_2100000,3001791,3001795,3002193,300...",0,2,NaN,OPPO A57,1,2,6.0.1,android,1577884,230001710,3011304,101900_101902,1003544,2342152,8390229093704413749,100.0,iqy_2,2071234.0,iqy_1000000000381-1-15-15,3,1280,720,True,False,False,False,False,False,0A421D7B11EABFC5,0
4,2035477570591176488,2190220024,137103102109100,137103102100100,NaN,1,2,Apple,iPhone 7,3,1,11.1.1,ios,1432367,230000063,2304491,102400_102401,1000023,2305409,8390208550469153745,103.0,NaN,1030051.0,xf_6C4DCB36DBE7EB12CE55EDF319FF8D93,8,960,640,True,False,False,False,False,False,B4734117F35EE97F,0

In [10]:
test = pd.read_table('./data/round1_iflyad_test_feature.txt')
test.head()

,instance_id,time,city,province,user_tags,carrier,devtype,make,model,nnt,os,osv,os_name,adid,advert_id,orderid,advert_industry_inner,campaign_id,creative_id,creative_tp_dnf,app_cate_id,f_channel,app_id,inner_slot_id,creative_type,creative_width,creative_height,creative_is_jump,creative_is_download,creative_is_js,creative_is_voicead,creative_has_deeplink,app_paid,advert_name
0,6930856710792380886,2190675456,137103104101100,137103104100100,NaN,2,2,Apple,iPhone 8 Plus,1,1,11.4.1,ios,1518579,230000063,3006011,102400_102401,1000023,2316955,8390430283595430291,103.0,NaN,1030051.0,xf_6C4DCB36DBE7EB12CE55EDF319FF8D93,8,960,640,True,False,False,False,False,False,B4734117F35EE97F
1,5460409694420131920,2190674821,137103104112100,137103104100100,"3004406,3004430,3004434",1,2,vivo,vivo X9Plus,1,2,7.1.2,android,1580740,230000063,3005949,102400_102401,1000023,2334795,8390430283595430291,108.0,NaN,1080001.0,xf_826A5605FD0EBC210098D47779C21CBE,8,960,640,True,False,False,False,False,False,B4734117F35EE97F
2,982813438159141507,2190674111,137105103101100,137105103100100,"3003779,3003843,3003851,3003863,3003865,300386...",2,2,OPPO A73t,OPPO A73t,4,2,7.1.1,android,1585472,230000063,3012756,102400_102401,1000023,2313211,8390465404427801098,111.0,NaN,1110016.0,xf_EE10823F5C5D57FF941653A9B5BA7B07,5,160,640,True,False,False,False,False,False,B4734117F35EE97F
3,529991959116679673,2190675256,137106101107100,137106101100100,NaN,2,2,vivo Z1,vivo Z1,4,2,8.1.0,android,1575100,230000063,2311393,102400_102401,1000023,2334795,8390430283595430291,111.0,NaN,1110016.0,xf_9EFA0BFCFEDCE6FF7B644299ACB88167,8,960,640,True,False,False,False,False,False,B4734117F35EE97F
4,5357053206615171780,2190673926,137103102101100,137103102100100,"2100191,2100041,2100078,2100136,2100042,300182...",3,2,HUAWEI,HUAWEI MLA-AL10,4,2,6.0,android,1584212,230000191,3012566,101700_101704,1003348,2338134,8390272894417697957,107.0,NaN,1000049.0,xf_64FAC0085FC8DC679F6BF49A1F98445D,5,320,480,True,False,False,False,False,False,42A4CB9035B7F50E

In [12]:
test.shape

(40024, 34)