# 两个规则都是0.511

In [35]:
import gc
from tqdm import tqdm, tqdm_notebook
from sklearn.model_selection import StratifiedKFold, KFold
from sklearn.metrics import f1_score, roc_auc_score
import datetime
import time
import lightgbm as lgb
import xgboost as xgb
import catboost as ctb
import numpy as np
import pandas as pd
import os
import math

import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
warnings.filterwarnings('ignore')

In [2]:
train_sales  = pd.read_csv('train_sales_data.csv')
evaluation_public = pd.read_csv('evaluation_public.csv')
submit_example    = pd.read_csv('submit_example.csv')

In [3]:
day_map = {1:31,2:28,3:31,4:30,5:31,6:30,7:31,8:31,9:30,10:31,11:30,12:31}
train_sales['daycount']=train_sales['regMonth'].map(day_map)
train_sales.loc[(train_sales.regMonth==2)&(train_sales.regYear==2016),'daycount']=29
train_sales['salesVolume']/=train_sales['daycount']
train_sales.head(10)

,province,adcode,model,bodyType,regYear,regMonth,salesVolume,daycount
0,上海,310000,3c974920a76ac9c1,SUV,2016,1,9.419355,31
1,云南,530000,3c974920a76ac9c1,SUV,2016,1,15.032258,31
2,内蒙古,150000,3c974920a76ac9c1,SUV,2016,1,8.290323,31
3,北京,110000,3c974920a76ac9c1,SUV,2016,1,13.161290,31
4,四川,510000,3c974920a76ac9c1,SUV,2016,1,19.677419,31
5,安徽,340000,3c974920a76ac9c1,SUV,2016,1,6.645161,31
6,山东,370000,3c974920a76ac9c1,SUV,2016,1,16.225806,31
7,山西,140000,3c974920a76ac9c1,SUV,2016,1,7.612903,31
8,广东,440000,3c974920a76ac9c1,SUV,2016,1,117.258065,31
9,广西,450000,3c974920a76ac9c1,SUV,2016,1,14.516129,31

In [4]:
train_sales2 = train_sales.set_index(["adcode", "bodyType", "model", "province","regYear", "regMonth"])[["salesVolume"]].unstack(level=-1)
train_sales2.head(10)

                                                   salesVolume             \
regMonth                                                    1          2
adcode bodyType  model            province regYear
110000 Hatchback 3e21824be728cbec 北京       2016      10.161290   3.448276
                                           2017       3.000000   2.142857
                 7a7885e2d7c00bcf 北京       2016      26.354839  14.689655
                                           2017      15.193548  18.678571
                 b4be3a4917289c82 北京       2016       5.645161   3.655172
                                           2017       3.000000   4.178571
       MPV       17bc272c93f19d56 北京       2016      14.709677   4.310345
                                           2017       4.870968   3.285714
                 79de4e4b24c35b04 北京       2016      29.677419   6.000000
                                           2017       5.741935   4.535714

                                                                          \
regMonth                                                   3          4
adcode bodyType  model            province regYear
110000 Hatchback 3e21824be728cbec 北京       2016      6.419355   5.433333
                                           2017      2.806452   1.400000
                 7a7885e2d7c00bcf 北京       2016     32.806452  28.200000
                                           2017     26.806452  23.266667
                 b4be3a4917289c82 北京       2016      8.096774   8.900000
                                           2017      4.935484   4.566667
       MPV       17bc272c93f19d56 北京       2016      9.806452   8.200000
                                           2017      6.354839   4.133333
                 79de4e4b24c35b04 北京       2016      9.161290  11.733333
                                           2017      6.419355   4.233333

                                                                          \
regMonth                                                   5          6
adcode bodyType  model            province regYear
110000 Hatchback 3e21824be728cbec 北京       2016      3.838710   4.700000
                                           2017      1.516129   1.566667
                 7a7885e2d7c00bcf 北京       2016     29.548387  27.533333
                                           2017     23.032258  22.133333
                 b4be3a4917289c82 北京       2016      8.354839   6.400000
                                           2017      4.483871   3.133333
       MPV       17bc272c93f19d56 北京       2016      8.967742   5.433333
                                           2017      4.258065   3.733333
                 79de4e4b24c35b04 北京       2016     12.129032   6.466667
                                           2017      4.129032   4.400000

                                                                          \
regMonth                                                   7          8
adcode bodyType  model            province regYear
110000 Hatchback 3e21824be728cbec 北京       2016      5.290323   4.483871
                                           2017      1.290323   1.322581
                 7a7885e2d7c00bcf 北京       2016     28.354839  29.387097
                                           2017     19.903226  18.032258
                 b4be3a4917289c82 北京       2016      5.548387   6.548387
                                           2017      2.838710   3.612903
       MPV       17bc272c93f19d56 北京       2016      5.774194   6.516129
                                           2017      3.258065   2.580645
                 79de4e4b24c35b04 北京       2016      7.741935  10.096774
                                           2017      3.741935   3.387097

                                                                          \
regMonth                                                   9          10
adcode bodyType  model            province regYear
110000 Hatchback 3e21824be728cbec 北京       2016      6.766667   5.419355
                                           2017      1.833333   1.903226
                 7a7885e2d7c00bcf 北京       2016     35.800000  29.516129
                                           2017     21.833333  15.548387
                 b4be3a4917289c82 北京       2016      7.733333   6.451613
                                           2017      5.433333   5.451613
       MPV       17bc272c93f19d56 北京       2016      8.066667   6.419355
                                           2017      4.533333   3.419355
                 79de4e4b24c35b04 北京       2016     12.333333  10.645161
                                           2017      3.033333   2.709677


regMonth                                                   11         12
adcode bodyType  model            province regYear
110000 Hatchback 3e21824be728cbec 北京       2016      7.400000   7.806452
                                           2017      1.766667   3.096774
                 7a7885e2d7c00bcf 北京       2016     38.733333  52.096774
                                           2017     24.200000  23.838710
                 b4be3a4917289c82 北京       2016      7.666667   7.290323
                                           2017      4.933333   9.161290
       MPV       17bc272c93f19d56 北京       2016     10.166667  16.580645
                                           2017      3.866667   5.677419
                 79de4e4b24c35b04 北京       2016     14.866667  27.483871
                                           2017      4.200000   5.290323

In [5]:
train_sales2.columns=['1','2','3','4','5','6','7','8','9','10','11','12']
train_sales2.head(10)

                                                            1          2  \
adcode bodyType  model            province regYear
110000 Hatchback 3e21824be728cbec 北京       2016     10.161290   3.448276
                                           2017      3.000000   2.142857
                 7a7885e2d7c00bcf 北京       2016     26.354839  14.689655
                                           2017     15.193548  18.678571
                 b4be3a4917289c82 北京       2016      5.645161   3.655172
                                           2017      3.000000   4.178571
       MPV       17bc272c93f19d56 北京       2016     14.709677   4.310345
                                           2017      4.870968   3.285714
                 79de4e4b24c35b04 北京       2016     29.677419   6.000000
                                           2017      5.741935   4.535714

                                                            3          4  \
adcode bodyType  model            province regYear
110000 Hatchback 3e21824be728cbec 北京       2016      6.419355   5.433333
                                           2017      2.806452   1.400000
                 7a7885e2d7c00bcf 北京       2016     32.806452  28.200000
                                           2017     26.806452  23.266667
                 b4be3a4917289c82 北京       2016      8.096774   8.900000
                                           2017      4.935484   4.566667
       MPV       17bc272c93f19d56 北京       2016      9.806452   8.200000
                                           2017      6.354839   4.133333
                 79de4e4b24c35b04 北京       2016      9.161290  11.733333
                                           2017      6.419355   4.233333

                                                            5          6  \
adcode bodyType  model            province regYear
110000 Hatchback 3e21824be728cbec 北京       2016      3.838710   4.700000
                                           2017      1.516129   1.566667
                 7a7885e2d7c00bcf 北京       2016     29.548387  27.533333
                                           2017     23.032258  22.133333
                 b4be3a4917289c82 北京       2016      8.354839   6.400000
                                           2017      4.483871   3.133333
       MPV       17bc272c93f19d56 北京       2016      8.967742   5.433333
                                           2017      4.258065   3.733333
                 79de4e4b24c35b04 北京       2016     12.129032   6.466667
                                           2017      4.129032   4.400000

                                                            7          8  \
adcode bodyType  model            province regYear
110000 Hatchback 3e21824be728cbec 北京       2016      5.290323   4.483871
                                           2017      1.290323   1.322581
                 7a7885e2d7c00bcf 北京       2016     28.354839  29.387097
                                           2017     19.903226  18.032258
                 b4be3a4917289c82 北京       2016      5.548387   6.548387
                                           2017      2.838710   3.612903
       MPV       17bc272c93f19d56 北京       2016      5.774194   6.516129
                                           2017      3.258065   2.580645
                 79de4e4b24c35b04 北京       2016      7.741935  10.096774
                                           2017      3.741935   3.387097

                                                            9         10  \
adcode bodyType  model            province regYear
110000 Hatchback 3e21824be728cbec 北京       2016      6.766667   5.419355
                                           2017      1.833333   1.903226
                 7a7885e2d7c00bcf 北京       2016     35.800000  29.516129
                                           2017     21.833333  15.548387
                 b4be3a4917289c82 北京       2016      7.733333   6.451613
                                           2017      5.433333   5.451613
       MPV       17bc272c93f19d56 北京       2016      8.066667   6.419355
                                           2017      4.533333   3.419355
                 79de4e4b24c35b04 北京       2016     12.333333  10.645161
                                           2017      3.033333   2.709677

                                                           11         12
adcode bodyType  model            province regYear
110000 Hatchback 3e21824be728cbec 北京       2016      7.400000   7.806452
                                           2017      1.766667   3.096774
                 7a7885e2d7c00bcf 北京       2016     38.733333  52.096774
                                           2017     24.200000  23.838710
                 b4be3a4917289c82 北京       2016      7.666667   7.290323
                                           2017      4.933333   9.161290
       MPV       17bc272c93f19d56 北京       2016     10.166667  16.580645
                                           2017      3.866667   5.677419
                 79de4e4b24c35b04 北京       2016     14.866667  27.483871
                                           2017      4.200000   5.290323

In [6]:
train_sales2["Mean"] = train_sales2.mean(axis=1)
train_sales2["Median"] = train_sales2.median(axis=1)
train_sales2.head(10)

                                                            1          2  \
adcode bodyType  model            province regYear
110000 Hatchback 3e21824be728cbec 北京       2016     10.161290   3.448276
                                           2017      3.000000   2.142857
                 7a7885e2d7c00bcf 北京       2016     26.354839  14.689655
                                           2017     15.193548  18.678571
                 b4be3a4917289c82 北京       2016      5.645161   3.655172
                                           2017      3.000000   4.178571
       MPV       17bc272c93f19d56 北京       2016     14.709677   4.310345
                                           2017      4.870968   3.285714
                 79de4e4b24c35b04 北京       2016     29.677419   6.000000
                                           2017      5.741935   4.535714

                                                            3          4  \
adcode bodyType  model            province regYear
110000 Hatchback 3e21824be728cbec 北京       2016      6.419355   5.433333
                                           2017      2.806452   1.400000
                 7a7885e2d7c00bcf 北京       2016     32.806452  28.200000
                                           2017     26.806452  23.266667
                 b4be3a4917289c82 北京       2016      8.096774   8.900000
                                           2017      4.935484   4.566667
       MPV       17bc272c93f19d56 北京       2016      9.806452   8.200000
                                           2017      6.354839   4.133333
                 79de4e4b24c35b04 北京       2016      9.161290  11.733333
                                           2017      6.419355   4.233333

                                                            5          6  \
adcode bodyType  model            province regYear
110000 Hatchback 3e21824be728cbec 北京       2016      3.838710   4.700000
                                           2017      1.516129   1.566667
                 7a7885e2d7c00bcf 北京       2016     29.548387  27.533333
                                           2017     23.032258  22.133333
                 b4be3a4917289c82 北京       2016      8.354839   6.400000
                                           2017      4.483871   3.133333
       MPV       17bc272c93f19d56 北京       2016      8.967742   5.433333
                                           2017      4.258065   3.733333
                 79de4e4b24c35b04 北京       2016     12.129032   6.466667
                                           2017      4.129032   4.400000

                                                            7          8  \
adcode bodyType  model            province regYear
110000 Hatchback 3e21824be728cbec 北京       2016      5.290323   4.483871
                                           2017      1.290323   1.322581
                 7a7885e2d7c00bcf 北京       2016     28.354839  29.387097
                                           2017     19.903226  18.032258
                 b4be3a4917289c82 北京       2016      5.548387   6.548387
                                           2017      2.838710   3.612903
       MPV       17bc272c93f19d56 北京       2016      5.774194   6.516129
                                           2017      3.258065   2.580645
                 79de4e4b24c35b04 北京       2016      7.741935  10.096774
                                           2017      3.741935   3.387097

                                                            9         10  \
adcode bodyType  model            province regYear
110000 Hatchback 3e21824be728cbec 北京       2016      6.766667   5.419355
                                           2017      1.833333   1.903226
                 7a7885e2d7c00bcf 北京       2016     35.800000  29.516129
                                           2017     21.833333  15.548387
                 b4be3a4917289c82 北京       2016      7.733333   6.451613
                                           2017      5.433333   5.451613
       MPV       17bc272c93f19d56 北京       2016      8.066667   6.419355
                                           2017      4.533333   3.419355
                 79de4e4b24c35b04 北京       2016     12.333333  10.645161
                                           2017      3.033333   2.709677

                                                           11         12  \
adcode bodyType  model            province regYear
110000 Hatchback 3e21824be728cbec 北京       2016      7.400000   7.806452
                                           2017      1.766667   3.096774
                 7a7885e2d7c00bcf 北京       2016     38.733333  52.096774
                                           2017     24.200000  23.838710
                 b4be3a4917289c82 北京       2016      7.666667   7.290323
                                           2017      4.933333   9.161290
       MPV       17bc272c93f19d56 北京       2016     10.166667  16.580645
                                           2017      3.866667   5.677419
                 79de4e4b24c35b04 北京       2016     14.866667  27.483871
                                           2017      4.200000   5.290323

                                                         Mean     Median
adcode bodyType  model            province regYear
110000 Hatchback 3e21824be728cbec 北京       2016      5.930636   5.433333
                                           2017      1.970417   1.833333
                 7a7885e2d7c00bcf 北京       2016     31.085070  29.516129
                                           2017     21.038895  21.833333
                 b4be3a4917289c82 北京       2016      6.857555   6.857555
                                           2017      4.644092   4.566667
       MPV       17bc272c93f19d56 北京       2016      8.745934   8.200000
                                           2017      4.164311   4.133333
                 79de4e4b24c35b04 北京       2016     13.194624  11.733333
                                           2017      4.318478   4.233333

In [7]:
train_sales2['quarter1_mean']=(train_sales2['1']+train_sales2['2']+train_sales2['3'])/3
train_sales2['quarter2_mean']=(train_sales2['4']+train_sales2['5']+train_sales2['6'])/3
train_sales2=train_sales2.unstack("regYear")
train_sales2.head(10)

                                                    1                     2  \
regYear                                          2016       2017       2016
adcode bodyType  model            province
110000 Hatchback 3e21824be728cbec 北京        10.161290   3.000000   3.448276
                 7a7885e2d7c00bcf 北京        26.354839  15.193548  14.689655
                 b4be3a4917289c82 北京         5.645161   3.000000   3.655172
       MPV       17bc272c93f19d56 北京        14.709677   4.870968   4.310345
                 79de4e4b24c35b04 北京        29.677419   5.741935   6.000000
                 7aab7fca2470987e 北京        13.096774  13.677419   5.344828
                 c06a2a387c0ee510 北京        34.548387  43.612903  12.448276
                 f270f6a489c6a9d7 北京        13.193548   3.419355   5.379310
       SUV       17363f08d683d52b 北京        18.709677   4.000000   5.586207
                 2a2ab41f8f6ff1cb 北京        14.774194   6.838710   2.482759

                                                               3             \
regYear                                          2017       2016       2017
adcode bodyType  model            province
110000 Hatchback 3e21824be728cbec 北京         2.142857   6.419355   2.806452
                 7a7885e2d7c00bcf 北京        18.678571  32.806452  26.806452
                 b4be3a4917289c82 北京         4.178571   8.096774   4.935484
       MPV       17bc272c93f19d56 北京         3.285714   9.806452   6.354839
                 79de4e4b24c35b04 北京         4.535714   9.161290   6.419355
                 7aab7fca2470987e 北京         8.714286  11.032258  12.193548
                 c06a2a387c0ee510 北京        39.785714  27.967742  48.645161
                 f270f6a489c6a9d7 北京         4.214286   7.387097   5.064516
       SUV       17363f08d683d52b 北京         2.892857   8.225806   2.096774
                 2a2ab41f8f6ff1cb 北京         3.642857   5.225806   5.806452

                                                    4                     5  \
regYear                                          2016       2017       2016
adcode bodyType  model            province
110000 Hatchback 3e21824be728cbec 北京         5.433333   1.400000   3.838710
                 7a7885e2d7c00bcf 北京        28.200000  23.266667  29.548387
                 b4be3a4917289c82 北京         8.900000   4.566667   8.354839
       MPV       17bc272c93f19d56 北京         8.200000   4.133333   8.967742
                 79de4e4b24c35b04 北京        11.733333   4.233333  12.129032
                 7aab7fca2470987e 北京        12.833333  10.666667  11.967742
                 c06a2a387c0ee510 北京        29.066667  37.733333  29.870968
                 f270f6a489c6a9d7 北京         7.766667   4.000000   6.903226
       SUV       17363f08d683d52b 北京         7.466667   1.600000   6.935484
                 2a2ab41f8f6ff1cb 北京         8.666667   4.733333  10.451613

                                                         ...             12  \
regYear                                          2017    ...           2016
adcode bodyType  model            province               ...
110000 Hatchback 3e21824be728cbec 北京         1.516129    ...       7.806452
                 7a7885e2d7c00bcf 北京        23.032258    ...      52.096774
                 b4be3a4917289c82 北京         4.483871    ...       7.290323
       MPV       17bc272c93f19d56 北京         4.258065    ...      16.580645
                 79de4e4b24c35b04 北京         4.129032    ...      27.483871
                 7aab7fca2470987e 北京         7.870968    ...      16.483871
                 c06a2a387c0ee510 北京        46.129032    ...      52.483871
                 f270f6a489c6a9d7 北京         3.548387    ...      16.258065
       SUV       17363f08d683d52b 北京         0.935484    ...       8.935484
                 2a2ab41f8f6ff1cb 北京         4.000000    ...      19.290323

                                                            Mean             \
regYear                                          2017       2016       2017
adcode bodyType  model            province
110000 Hatchback 3e21824be728cbec 北京         3.096774   5.930636   1.970417
                 7a7885e2d7c00bcf 北京        23.838710  31.085070  21.038895
                 b4be3a4917289c82 北京         9.161290   6.857555   4.644092
       MPV       17bc272c93f19d56 北京         5.677419   8.745934   4.164311
                 79de4e4b24c35b04 北京         5.290323  13.194624   4.318478
                 7aab7fca2470987e 北京         6.967742  12.502929   9.194918
                 c06a2a387c0ee510 北京        43.806452  30.045958  44.623720
                 f270f6a489c6a9d7 北京        10.354839   8.639405   3.900742
       SUV       17363f08d683d52b 北京         3.516129   8.213008   1.723150
                 2a2ab41f8f6ff1cb 北京         3.322581  11.502864   4.293804

                                               Median             \
regYear                                          2016       2017
adcode bodyType  model            province
110000 Hatchback 3e21824be728cbec 北京         5.433333   1.833333
                 7a7885e2d7c00bcf 北京        29.516129  21.833333
                 b4be3a4917289c82 北京         6.857555   4.566667
       MPV       17bc272c93f19d56 北京         8.200000   4.133333
                 79de4e4b24c35b04 北京        11.733333   4.233333
                 7aab7fca2470987e 北京        12.806452   8.666667
                 c06a2a387c0ee510 北京        29.870968  44.623720
                 f270f6a489c6a9d7 北京         7.677419   3.466667
       SUV       17363f08d683d52b 北京         7.466667   1.600000
                 2a2ab41f8f6ff1cb 北京        11.502864   4.200000

                                           quarter1_mean             \
regYear                                             2016       2017
adcode bodyType  model            province
110000 Hatchback 3e21824be728cbec 北京            6.676307   2.649770
                 7a7885e2d7c00bcf 北京           24.616982  20.226190
                 b4be3a4917289c82 北京            5.799036   4.038018
       MPV       17bc272c93f19d56 北京            9.608825   4.837174
                 79de4e4b24c35b04 北京           14.946237   5.565668
                 7aab7fca2470987e 北京            9.824620  11.528418
                 c06a2a387c0ee510 北京           24.988135  44.014593
                 f270f6a489c6a9d7 北京            8.653319   4.232719
       SUV       17363f08d683d52b 北京           10.840564   2.996544
                 2a2ab41f8f6ff1cb 北京            7.494253   5.429339

                                           quarter2_mean
regYear                                             2016       2017
adcode bodyType  model            province
110000 Hatchback 3e21824be728cbec 北京            4.657348   1.494265
                 7a7885e2d7c00bcf 北京           28.427240  22.810753
                 b4be3a4917289c82 北京            7.884946   4.061290
       MPV       17bc272c93f19d56 北京            7.533692   4.041577
                 79de4e4b24c35b04 北京           10.109677   4.254122
                 7aab7fca2470987e 北京           12.844803   9.068100
                 c06a2a387c0ee510 北京           28.801434  46.509677
                 f270f6a489c6a9d7 北京            6.812186   3.671685
       SUV       17363f08d683d52b 北京            7.056272   1.134050
                 2a2ab41f8f6ff1cb 北京           10.050538   3.944444

[10 rows x 32 columns]

In [9]:
train_sales2.columns= ["_".join([str(i) for i in x]) for x in train_sales2.columns.ravel()]
train_sales2.head(10)

                                               1_2016     1_2017     2_2016  \
adcode bodyType  model            province
110000 Hatchback 3e21824be728cbec 北京        10.161290   3.000000   3.448276
                 7a7885e2d7c00bcf 北京        26.354839  15.193548  14.689655
                 b4be3a4917289c82 北京         5.645161   3.000000   3.655172
       MPV       17bc272c93f19d56 北京        14.709677   4.870968   4.310345
                 79de4e4b24c35b04 北京        29.677419   5.741935   6.000000
                 7aab7fca2470987e 北京        13.096774  13.677419   5.344828
                 c06a2a387c0ee510 北京        34.548387  43.612903  12.448276
                 f270f6a489c6a9d7 北京        13.193548   3.419355   5.379310
       SUV       17363f08d683d52b 北京        18.709677   4.000000   5.586207
                 2a2ab41f8f6ff1cb 北京        14.774194   6.838710   2.482759

                                               2_2017     3_2016     3_2017  \
adcode bodyType  model            province
110000 Hatchback 3e21824be728cbec 北京         2.142857   6.419355   2.806452
                 7a7885e2d7c00bcf 北京        18.678571  32.806452  26.806452
                 b4be3a4917289c82 北京         4.178571   8.096774   4.935484
       MPV       17bc272c93f19d56 北京         3.285714   9.806452   6.354839
                 79de4e4b24c35b04 北京         4.535714   9.161290   6.419355
                 7aab7fca2470987e 北京         8.714286  11.032258  12.193548
                 c06a2a387c0ee510 北京        39.785714  27.967742  48.645161
                 f270f6a489c6a9d7 北京         4.214286   7.387097   5.064516
       SUV       17363f08d683d52b 北京         2.892857   8.225806   2.096774
                 2a2ab41f8f6ff1cb 北京         3.642857   5.225806   5.806452

                                               4_2016     4_2017     5_2016  \
adcode bodyType  model            province
110000 Hatchback 3e21824be728cbec 北京         5.433333   1.400000   3.838710
                 7a7885e2d7c00bcf 北京        28.200000  23.266667  29.548387
                 b4be3a4917289c82 北京         8.900000   4.566667   8.354839
       MPV       17bc272c93f19d56 北京         8.200000   4.133333   8.967742
                 79de4e4b24c35b04 北京        11.733333   4.233333  12.129032
                 7aab7fca2470987e 北京        12.833333  10.666667  11.967742
                 c06a2a387c0ee510 北京        29.066667  37.733333  29.870968
                 f270f6a489c6a9d7 北京         7.766667   4.000000   6.903226
       SUV       17363f08d683d52b 北京         7.466667   1.600000   6.935484
                 2a2ab41f8f6ff1cb 北京         8.666667   4.733333  10.451613

                                               5_2017         ...          \
adcode bodyType  model            province                    ...
110000 Hatchback 3e21824be728cbec 北京         1.516129         ...
                 7a7885e2d7c00bcf 北京        23.032258         ...
                 b4be3a4917289c82 北京         4.483871         ...
       MPV       17bc272c93f19d56 北京         4.258065         ...
                 79de4e4b24c35b04 北京         4.129032         ...
                 7aab7fca2470987e 北京         7.870968         ...
                 c06a2a387c0ee510 北京        46.129032         ...
                 f270f6a489c6a9d7 北京         3.548387         ...
       SUV       17363f08d683d52b 北京         0.935484         ...
                 2a2ab41f8f6ff1cb 北京         4.000000         ...

                                              12_2016    12_2017  Mean_2016  \
adcode bodyType  model            province
110000 Hatchback 3e21824be728cbec 北京         7.806452   3.096774   5.930636
                 7a7885e2d7c00bcf 北京        52.096774  23.838710  31.085070
                 b4be3a4917289c82 北京         7.290323   9.161290   6.857555
       MPV       17bc272c93f19d56 北京        16.580645   5.677419   8.745934
                 79de4e4b24c35b04 北京        27.483871   5.290323  13.194624
                 7aab7fca2470987e 北京        16.483871   6.967742  12.502929
                 c06a2a387c0ee510 北京        52.483871  43.806452  30.045958
                 f270f6a489c6a9d7 北京        16.258065  10.354839   8.639405
       SUV       17363f08d683d52b 北京         8.935484   3.516129   8.213008
                 2a2ab41f8f6ff1cb 北京        19.290323   3.322581  11.502864

                                            Mean_2017  Median_2016  \
adcode bodyType  model            province
110000 Hatchback 3e21824be728cbec 北京         1.970417     5.433333
                 7a7885e2d7c00bcf 北京        21.038895    29.516129
                 b4be3a4917289c82 北京         4.644092     6.857555
       MPV       17bc272c93f19d56 北京         4.164311     8.200000
                 79de4e4b24c35b04 北京         4.318478    11.733333
                 7aab7fca2470987e 北京         9.194918    12.806452
                 c06a2a387c0ee510 北京        44.623720    29.870968
                 f270f6a489c6a9d7 北京         3.900742     7.677419
       SUV       17363f08d683d52b 北京         1.723150     7.466667
                 2a2ab41f8f6ff1cb 北京         4.293804    11.502864

                                            Median_2017  quarter1_mean_2016  \
adcode bodyType  model            province
110000 Hatchback 3e21824be728cbec 北京           1.833333            6.676307
                 7a7885e2d7c00bcf 北京          21.833333           24.616982
                 b4be3a4917289c82 北京           4.566667            5.799036
       MPV       17bc272c93f19d56 北京           4.133333            9.608825
                 79de4e4b24c35b04 北京           4.233333           14.946237
                 7aab7fca2470987e 北京           8.666667            9.824620
                 c06a2a387c0ee510 北京          44.623720           24.988135
                 f270f6a489c6a9d7 北京           3.466667            8.653319
       SUV       17363f08d683d52b 北京           1.600000           10.840564
                 2a2ab41f8f6ff1cb 北京           4.200000            7.494253

                                            quarter1_mean_2017  \
adcode bodyType  model            province
110000 Hatchback 3e21824be728cbec 北京                  2.649770
                 7a7885e2d7c00bcf 北京                 20.226190
                 b4be3a4917289c82 北京                  4.038018
       MPV       17bc272c93f19d56 北京                  4.837174
                 79de4e4b24c35b04 北京                  5.565668
                 7aab7fca2470987e 北京                 11.528418
                 c06a2a387c0ee510 北京                 44.014593
                 f270f6a489c6a9d7 北京                  4.232719
       SUV       17363f08d683d52b 北京                  2.996544
                 2a2ab41f8f6ff1cb 北京                  5.429339

                                            quarter2_mean_2016  \
adcode bodyType  model            province
110000 Hatchback 3e21824be728cbec 北京                  4.657348
                 7a7885e2d7c00bcf 北京                 28.427240
                 b4be3a4917289c82 北京                  7.884946
       MPV       17bc272c93f19d56 北京                  7.533692
                 79de4e4b24c35b04 北京                 10.109677
                 7aab7fca2470987e 北京                 12.844803
                 c06a2a387c0ee510 北京                 28.801434
                 f270f6a489c6a9d7 北京                  6.812186
       SUV       17363f08d683d52b 北京                  7.056272
                 2a2ab41f8f6ff1cb 北京                 10.050538

                                            quarter2_mean_2017
adcode bodyType  model            province
110000 Hatchback 3e21824be728cbec 北京                  1.494265
                 7a7885e2d7c00bcf 北京                 22.810753
                 b4be3a4917289c82 北京                  4.061290
       MPV       17bc272c93f19d56 北京                  4.041577
                 79de4e4b24c35b04 北京                  4.254122
                 7aab7fca2470987e 北京                  9.068100
                 c06a2a387c0ee510 北京                 46.509677
                 f270f6a489c6a9d7 北京                  3.671685
       SUV       17363f08d683d52b 北京                  1.134050
                 2a2ab41f8f6ff1cb 北京                  3.944444

[10 rows x 32 columns]

In [10]:
train_sales2 = train_sales2.reset_index()
train_sales2.head(10)

,adcode,bodyType,model,province,1_2016,1_2017,2_2016,2_2017,3_2016,3_2017,...,12_2016,12_2017,Mean_2016,Mean_2017,Median_2016,Median_2017,quarter1_mean_2016,quarter1_mean_2017,quarter2_mean_2016,quarter2_mean_2017
0,110000,Hatchback,3e21824be728cbec,北京,10.161290,3.000000,3.448276,2.142857,6.419355,2.806452,...,7.806452,3.096774,5.930636,1.970417,5.433333,1.833333,6.676307,2.649770,4.657348,1.494265
1,110000,Hatchback,7a7885e2d7c00bcf,北京,26.354839,15.193548,14.689655,18.678571,32.806452,26.806452,...,52.096774,23.838710,31.085070,21.038895,29.516129,21.833333,24.616982,20.226190,28.427240,22.810753
2,110000,Hatchback,b4be3a4917289c82,北京,5.645161,3.000000,3.655172,4.178571,8.096774,4.935484,...,7.290323,9.161290,6.857555,4.644092,6.857555,4.566667,5.799036,4.038018,7.884946,4.061290
3,110000,MPV,17bc272c93f19d56,北京,14.709677,4.870968,4.310345,3.285714,9.806452,6.354839,...,16.580645,5.677419,8.745934,4.164311,8.200000,4.133333,9.608825,4.837174,7.533692,4.041577
4,110000,MPV,79de4e4b24c35b04,北京,29.677419,5.741935,6.000000,4.535714,9.161290,6.419355,...,27.483871,5.290323,13.194624,4.318478,11.733333,4.233333,14.946237,5.565668,10.109677,4.254122
5,110000,MPV,7aab7fca2470987e,北京,13.096774,13.677419,5.344828,8.714286,11.032258,12.193548,...,16.483871,6.967742,12.502929,9.194918,12.806452,8.666667,9.824620,11.528418,12.844803,9.068100
6,110000,MPV,c06a2a387c0ee510,北京,34.548387,43.612903,12.448276,39.785714,27.967742,48.645161,...,52.483871,43.806452,30.045958,44.623720,29.870968,44.623720,24.988135,44.014593,28.801434,46.509677
7,110000,MPV,f270f6a489c6a9d7,北京,13.193548,3.419355,5.379310,4.214286,7.387097,5.064516,...,16.258065,10.354839,8.639405,3.900742,7.677419,3.466667,8.653319,4.232719,6.812186,3.671685
8,110000,SUV,17363f08d683d52b,北京,18.709677,4.000000,5.586207,2.892857,8.225806,2.096774,...,8.935484,3.516129,8.213008,1.723150,7.466667,1.600000,10.840564,2.996544,7.056272,1.134050
9,110000,SUV,2a2ab41f8f6ff1cb,北京,14.774194,6.838710,2.482759,3.642857,5.225806,5.806452,...,19.290323,3.322581,11.502864,4.293804,11.502864,4.200000,7.494253,5.429339,10.050538,3.944444

In [11]:
train_sales2['20171_divide_20161']=train_sales2['1_2017']/train_sales2['1_2016']
train_sales2['20172_divide_20162']=train_sales2['2_2017']/train_sales2['2_2016']
train_sales2['20173_divide_20163']=train_sales2['3_2017']/train_sales2['3_2016']
train_sales2['20174_divide_20164']=train_sales2['4_2017']/train_sales2['4_2016']

train_sales2['2017y_divide_2016y_mean']=train_sales2['Mean_2017']/train_sales2['Mean_2016']
train_sales2['2017y_divide_2016y_median']=train_sales2['Median_2017']/train_sales2['Median_2016']
train_sales2['2017q1_divide_2016q1']=train_sales2['quarter1_mean_2017']/train_sales2['quarter1_mean_2016']
train_sales2['2017q2_divide_2016q2']=train_sales2['quarter2_mean_2017']/train_sales2['quarter2_mean_2016']

qushim1=(0.25*train_sales2['2017y_divide_2016y_mean']+0.25*train_sales2['2017y_divide_2016y_mean'])+0.3*train_sales2['2017q1_divide_2016q1']+0.2*train_sales2['20171_divide_20161']
qushim2=(0.25*train_sales2['2017y_divide_2016y_mean']+0.25*train_sales2['2017y_divide_2016y_mean'])+0.3*train_sales2['2017q1_divide_2016q1']+0.2*train_sales2['20172_divide_20162']
qushim3=(0.25*train_sales2['2017y_divide_2016y_mean']+0.25*train_sales2['2017y_divide_2016y_mean'])+0.3*train_sales2['2017q1_divide_2016q1']+0.2*train_sales2['20173_divide_20163']
qushim4=(0.25*train_sales2['2017y_divide_2016y_mean']+0.25*train_sales2['2017y_divide_2016y_mean'])+0.3*train_sales2['2017q2_divide_2016q2']+0.2*train_sales2['20174_divide_20164']


qushi1_v_2016=train_sales2['1_2016'].values* qushim1* qushim1
qushi2_v_2016=train_sales2['2_2016'].values* qushim2* qushim2
qushi3_v_2016=train_sales2['3_2016'].values* qushim3* qushim3
qushi4_v_2016=train_sales2['4_2016'].values* qushim4* qushim4

qushi1_v_2017=train_sales2['1_2017'].values* qushim1
qushi2_v_2017=train_sales2['2_2017'].values* qushim2
qushi3_v_2017=train_sales2['3_2017'].values* qushim3
qushi4_v_2017=train_sales2['4_2017'].values* qushim4

qushi1_v=qushi1_v_2016*0.3+qushi1_v_2017*0.7
qushi2_v=qushi2_v_2016*0.3+qushi2_v_2017*0.7
qushi3_v=qushi3_v_2016*0.3+qushi3_v_2017*0.7
qushi4_v=qushi4_v_2016*0.3+qushi4_v_2017*0.7

train_sales2['pre1']=qushi1_v
train_sales2['pre2']=qushi2_v
train_sales2['pre3']=qushi3_v
train_sales2['pre4']=qushi4_v

In [12]:
train_sales2.head(10)

,adcode,bodyType,model,province,1_2016,1_2017,2_2016,2_2017,3_2016,3_2017,...,20173_divide_20163,20174_divide_20164,2017y_divide_2016y_mean,2017y_divide_2016y_median,2017q1_divide_2016q1,2017q2_divide_2016q2,pre1,pre2,pre3,pre4
0,110000,Hatchback,3e21824be728cbec,北京,10.161290,3.000000,3.448276,2.142857,6.419355,2.806452,...,0.437186,0.257669,0.332244,0.337423,0.396892,0.320840,1.084129,0.787664,0.999430,0.468247
1,110000,Hatchback,7a7885e2d7c00bcf,北京,26.354839,15.193548,14.689655,18.678571,32.806452,26.806452,...,0.817109,0.825059,0.676817,0.739709,0.821636,0.802426,11.323318,14.076295,19.553208,16.804467
2,110000,Hatchback,b4be3a4917289c82,北京,5.645161,3.000000,3.655172,4.178571,8.096774,4.935484,...,0.609562,0.513109,0.677223,0.665932,0.696326,0.515069,2.096873,2.930802,3.401254,2.852070
3,110000,MPV,17bc272c93f19d56,北京,14.709677,4.870968,4.310345,3.285714,9.806452,6.354839,...,0.648026,0.504065,0.476143,0.504065,0.503409,0.536467,2.467377,1.624806,3.098901,2.060727
4,110000,MPV,79de4e4b24c35b04,北京,29.677419,5.741935,6.000000,4.535714,9.161290,6.419355,...,0.700704,0.360795,0.327291,0.360795,0.372379,0.420797,2.140426,1.681795,2.341551,1.534242
5,110000,MPV,7aab7fca2470987e,北京,13.096774,13.677419,5.344828,8.714286,11.032258,12.193548,...,1.105263,0.831169,0.735421,0.676742,1.173421,0.705974,12.278659,8.133256,10.959440,7.709241
6,110000,MPV,c06a2a387c0ee510,北京,34.548387,43.612903,12.448276,39.785714,27.967742,48.645161,...,1.739331,1.298165,1.485182,1.493883,1.761420,1.614839,70.567023,66.827098,77.114795,58.541049
7,110000,MPV,f270f6a489c6a9d7,北京,13.193548,3.419355,5.379310,4.214286,7.387097,5.064516,...,0.685590,0.515021,0.451506,0.451541,0.489144,0.538988,1.728327,2.012999,2.382207,1.933739
8,110000,SUV,17363f08d683d52b,北京,18.709677,4.000000,5.586207,2.892857,8.225806,2.096774,...,0.254902,0.214286,0.209807,0.214286,0.276420,0.160715,0.944090,0.732392,0.491247,0.305523
9,110000,SUV,2a2ab41f8f6ff1cb,北京,14.774194,6.838710,2.482759,3.642857,5.225806,5.806452,...,1.111111,0.546154,0.373281,0.365126,0.724467,0.392461,3.469925,2.140748,3.159971,1.815217

In [14]:
presale1 = train_sales2[["adcode", "bodyType", "model", "province",'pre1']].rename(columns={'pre1':'forecastVolum1'})
presale1.head(10)

   adcode   bodyType             model province  forecastVolum1
0  110000  Hatchback  3e21824be728cbec       北京        1.084129
1  110000  Hatchback  7a7885e2d7c00bcf       北京       11.323318
2  110000  Hatchback  b4be3a4917289c82       北京        2.096873
3  110000        MPV  17bc272c93f19d56       北京        2.467377
4  110000        MPV  79de4e4b24c35b04       北京        2.140426
5  110000        MPV  7aab7fca2470987e       北京       12.278659
6  110000        MPV  c06a2a387c0ee510       北京       70.567023
7  110000        MPV  f270f6a489c6a9d7       北京        1.728327
8  110000        SUV  17363f08d683d52b       北京        0.944090
9  110000        SUV  2a2ab41f8f6ff1cb       北京        3.469925

In [16]:
presale1['regMonth'] = 1
presale2 = train_sales2[["adcode", "bodyType", "model", "province", 'pre2']].rename(columns={'pre2':'forecastVolum1'})
presale2['regMonth'] = 2
presale3 = train_sales2[["adcode", "bodyType", "model", "province", 'pre3']].rename(columns={'pre3':'forecastVolum1'})
presale3['regMonth'] = 3
presale4 = train_sales2[["adcode", "bodyType", "model", "province", 'pre4']].rename(columns={'pre4':'forecastVolum1'})
presale4['regMonth'] = 4

In [17]:
result=pd.concat([presale1,presale2,presale3,presale4]).reset_index(drop=True)
result.head(10)

   adcode   bodyType  forecastVolum1             model province  regMonth
0  110000  Hatchback        1.084129  3e21824be728cbec       北京       NaN
1  110000  Hatchback       11.323318  7a7885e2d7c00bcf       北京       NaN
2  110000  Hatchback        2.096873  b4be3a4917289c82       北京       NaN
3  110000        MPV        2.467377  17bc272c93f19d56       北京       NaN
4  110000        MPV        2.140426  79de4e4b24c35b04       北京       NaN
5  110000        MPV       12.278659  7aab7fca2470987e       北京       NaN
6  110000        MPV       70.567023  c06a2a387c0ee510       北京       NaN
7  110000        MPV        1.728327  f270f6a489c6a9d7       北京       NaN
8  110000        SUV        0.944090  17363f08d683d52b       北京       NaN
9  110000        SUV        3.469925  2a2ab41f8f6ff1cb       北京       NaN

In [18]:
def rule1(train_sales):
    train_sales = train_sales.set_index(["adcode", "bodyType", "model", "province","regYear", "regMonth"])[["salesVolume"]].unstack(level=-1)
    train_sales.columns=['1','2','3','4','5','6','7','8','9','10','11','12']
    train_sales["Mean"] = train_sales.mean(axis=1)
    train_sales["Median"] = train_sales.median(axis=1)

    train_sales['quarter1_mean']=(train_sales['1']+train_sales['2']+train_sales['3'])/3
    train_sales['quarter2_mean']=(train_sales['4']+train_sales['5']+train_sales['6'])/3

    train_sales=train_sales.unstack("regYear")
    train_sales.columns= ["_".join([str(i) for i in x]) for x in train_sales.columns.ravel()]
    train_sales = train_sales.reset_index()
    train_sales['20171_divide_20161']=train_sales['1_2017']/train_sales['1_2016']
    train_sales['20172_divide_20162']=train_sales['2_2017']/train_sales['2_2016']
    train_sales['20173_divide_20163']=train_sales['3_2017']/train_sales['3_2016']
    train_sales['20174_divide_20164']=train_sales['4_2017']/train_sales['4_2016']

    train_sales['2017y_divide_2016y_mean']=train_sales['Mean_2017']/train_sales['Mean_2016']
    train_sales['2017y_divide_2016y_median']=train_sales['Median_2017']/train_sales['Median_2016']
    train_sales['2017q1_divide_2016q1']=train_sales['quarter1_mean_2017']/train_sales['quarter1_mean_2016']
    train_sales['2017q2_divide_2016q2']=train_sales['quarter2_mean_2017']/train_sales['quarter2_mean_2016']

    qushim1=(0.25*train_sales['2017y_divide_2016y_mean']+0.25*train_sales['2017y_divide_2016y_mean'])+0.3*train_sales['2017q1_divide_2016q1']+0.2*train_sales['20171_divide_20161']
    qushim2=(0.25*train_sales['2017y_divide_2016y_mean']+0.25*train_sales['2017y_divide_2016y_mean'])+0.3*train_sales['2017q1_divide_2016q1']+0.2*train_sales['20172_divide_20162']
    qushim3=(0.25*train_sales['2017y_divide_2016y_mean']+0.25*train_sales['2017y_divide_2016y_mean'])+0.3*train_sales['2017q1_divide_2016q1']+0.2*train_sales['20173_divide_20163']
    qushim4=(0.25*train_sales['2017y_divide_2016y_mean']+0.25*train_sales['2017y_divide_2016y_mean'])+0.3*train_sales['2017q2_divide_2016q2']+0.2*train_sales['20174_divide_20164']


    qushi1_v_2016=train_sales['1_2016'].values* qushim1* qushim1
    qushi2_v_2016=train_sales['2_2016'].values* qushim2* qushim2
    qushi3_v_2016=train_sales['3_2016'].values* qushim3* qushim3
    qushi4_v_2016=train_sales['4_2016'].values* qushim4* qushim4

    qushi1_v_2017=train_sales['1_2017'].values* qushim1
    qushi2_v_2017=train_sales['2_2017'].values* qushim2
    qushi3_v_2017=train_sales['3_2017'].values* qushim3
    qushi4_v_2017=train_sales['4_2017'].values* qushim4

    qushi1_v=qushi1_v_2016*0.3+qushi1_v_2017*0.7
    qushi2_v=qushi2_v_2016*0.3+qushi2_v_2017*0.7
    qushi3_v=qushi3_v_2016*0.3+qushi3_v_2017*0.7
    qushi4_v=qushi4_v_2016*0.3+qushi4_v_2017*0.7

    train_sales['pre1']=qushi1_v
    train_sales['pre2']=qushi2_v
    train_sales['pre3']=qushi3_v
    train_sales['pre4']=qushi4_v
    presale1 = train_sales[["adcode", "bodyType", "model", "province",'pre1']].rename(columns={'pre1':'forecastVolum1'})
    presale1['regMonth']=1
    presale2 = train_sales[["adcode", "bodyType", "model", "province", 'pre2']].rename(columns={'pre2':'forecastVolum1'})
    presale2['regMonth'] = 2
    presale3 = train_sales[["adcode", "bodyType", "model", "province", 'pre3']].rename(columns={'pre3':'forecastVolum1'})
    presale3['regMonth'] = 3
    presale4 = train_sales[["adcode", "bodyType", "model", "province", 'pre4']].rename(columns={'pre4':'forecastVolum1'})
    presale4['regMonth'] = 4

    result=pd.concat([presale1,presale2,presale3,presale4]).reset_index(drop=True)

    return result

rule1=rule1(train_sales.copy())

In [19]:
rule1.head(10)

   adcode   bodyType             model province  forecastVolum1  regMonth
0  110000  Hatchback  3e21824be728cbec       北京        1.084129         1
1  110000  Hatchback  7a7885e2d7c00bcf       北京       11.323318         1
2  110000  Hatchback  b4be3a4917289c82       北京        2.096873         1
3  110000        MPV  17bc272c93f19d56       北京        2.467377         1
4  110000        MPV  79de4e4b24c35b04       北京        2.140426         1
5  110000        MPV  7aab7fca2470987e       北京       12.278659         1
6  110000        MPV  c06a2a387c0ee510       北京       70.567023         1
7  110000        MPV  f270f6a489c6a9d7       北京        1.728327         1
8  110000        SUV  17363f08d683d52b       北京        0.944090         1
9  110000        SUV  2a2ab41f8f6ff1cb       北京        3.469925         1

In [20]:
def yulaorule(train_sales):
    m1_12 = train_sales.loc[(train_sales.regYear == 2017) & (train_sales.regMonth == 1), 'salesVolume'].values / \
            train_sales.loc[(train_sales.regYear == 2016) & (train_sales.regMonth == 12), 'salesVolume'].values
    m1_11 = train_sales.loc[(train_sales.regYear == 2017) & (train_sales.regMonth == 1), 'salesVolume'].values / \
            train_sales.loc[(train_sales.regYear == 2016) & (train_sales.regMonth == 11), 'salesVolume'].values
    m1_10 = train_sales.loc[(train_sales.regYear == 2017) & (train_sales.regMonth == 1), 'salesVolume'].values / \
            train_sales.loc[(train_sales.regYear == 2016) & (train_sales.regMonth == 10), 'salesVolume'].values
    m1_09 = train_sales.loc[(train_sales.regYear == 2017) & (train_sales.regMonth == 1), 'salesVolume'].values / \
            train_sales.loc[(train_sales.regYear == 2016) & (train_sales.regMonth == 9), 'salesVolume'].values
    m1_08 = train_sales.loc[(train_sales.regYear == 2017) & (train_sales.regMonth == 1), 'salesVolume'].values / \
            train_sales.loc[(train_sales.regYear == 2016) & (train_sales.regMonth == 8), 'salesVolume'].values

    m1_12_volum = train_sales.loc[
                      (train_sales.regYear == 2017) & (train_sales.regMonth == 12), 'salesVolume'].values * m1_12
    m1_11_volum = train_sales.loc[
                      (train_sales.regYear == 2017) & (train_sales.regMonth == 11), 'salesVolume'].values * m1_11
    m1_10_volum = train_sales.loc[
                      (train_sales.regYear == 2017) & (train_sales.regMonth == 10), 'salesVolume'].values * m1_10
    m1_09_volum = train_sales.loc[
                      (train_sales.regYear == 2017) & (train_sales.regMonth == 9), 'salesVolume'].values * m1_09
    m1_08_volum = train_sales.loc[
                      (train_sales.regYear == 2017) & (train_sales.regMonth == 8), 'salesVolume'].values * m1_08

    evaluation_public.loc[
        evaluation_public.regMonth == 1, 'forecastVolum'] = m1_12_volum / 2 + m1_11_volum / 4 + m1_10_volum / 8 + m1_09_volum / 16 + m1_08_volum / 16

    # 2018年1、2、3月，提取方式历史月份销量比例，考虑时间衰减，月份越近占比越高
    m16_1_2 = train_sales.loc[(train_sales.regYear == 2016) & (train_sales.regMonth == 1), 'salesVolume'].values / \
              train_sales.loc[(train_sales.regYear == 2016) & (train_sales.regMonth == 2), 'salesVolume'].values
    m16_1_3 = train_sales.loc[(train_sales.regYear == 2016) & (train_sales.regMonth == 1), 'salesVolume'].values / \
              train_sales.loc[(train_sales.regYear == 2016) & (train_sales.regMonth == 3), 'salesVolume'].values
    m16_1_4 = train_sales.loc[(train_sales.regYear == 2016) & (train_sales.regMonth == 1), 'salesVolume'].values / \
              train_sales.loc[(train_sales.regYear == 2016) & (train_sales.regMonth == 4), 'salesVolume'].values
    m16_1_5 = train_sales.loc[(train_sales.regYear == 2016) & (train_sales.regMonth == 1), 'salesVolume'].values / \
              train_sales.loc[(train_sales.regYear == 2016) & (train_sales.regMonth == 5), 'salesVolume'].values

    m16_2_3 = train_sales.loc[(train_sales.regYear == 2016) & (train_sales.regMonth == 2), 'salesVolume'].values / \
              train_sales.loc[(train_sales.regYear == 2016) & (train_sales.regMonth == 3), 'salesVolume'].values
    m16_2_4 = train_sales.loc[(train_sales.regYear == 2016) & (train_sales.regMonth == 2), 'salesVolume'].values / \
              train_sales.loc[(train_sales.regYear == 2016) & (train_sales.regMonth == 4), 'salesVolume'].values
    m16_2_5 = train_sales.loc[(train_sales.regYear == 2016) & (train_sales.regMonth == 2), 'salesVolume'].values / \
              train_sales.loc[(train_sales.regYear == 2016) & (train_sales.regMonth == 5), 'salesVolume'].values
    m16_2_6 = train_sales.loc[(train_sales.regYear == 2016) & (train_sales.regMonth == 2), 'salesVolume'].values / \
              train_sales.loc[(train_sales.regYear == 2016) & (train_sales.regMonth == 6), 'salesVolume'].values

    m16_3_4 = train_sales.loc[(train_sales.regYear == 2016) & (train_sales.regMonth == 3), 'salesVolume'].values / \
              train_sales.loc[(train_sales.regYear == 2016) & (train_sales.regMonth == 4), 'salesVolume'].values
    m16_3_5 = train_sales.loc[(train_sales.regYear == 2016) & (train_sales.regMonth == 3), 'salesVolume'].values / \
              train_sales.loc[(train_sales.regYear == 2016) & (train_sales.regMonth == 5), 'salesVolume'].values
    m16_3_6 = train_sales.loc[(train_sales.regYear == 2016) & (train_sales.regMonth == 3), 'salesVolume'].values / \
              train_sales.loc[(train_sales.regYear == 2016) & (train_sales.regMonth == 6), 'salesVolume'].values
    m16_3_7 = train_sales.loc[(train_sales.regYear == 2016) & (train_sales.regMonth == 3), 'salesVolume'].values / \
              train_sales.loc[(train_sales.regYear == 2016) & (train_sales.regMonth == 7), 'salesVolume'].values

    m17_1_2 = train_sales.loc[(train_sales.regYear == 2017) & (train_sales.regMonth == 1), 'salesVolume'].values / \
              train_sales.loc[(train_sales.regYear == 2017) & (train_sales.regMonth == 2), 'salesVolume'].values
    m17_1_3 = train_sales.loc[(train_sales.regYear == 2017) & (train_sales.regMonth == 1), 'salesVolume'].values / \
              train_sales.loc[(train_sales.regYear == 2017) & (train_sales.regMonth == 3), 'salesVolume'].values
    m17_1_4 = train_sales.loc[(train_sales.regYear == 2017) & (train_sales.regMonth == 1), 'salesVolume'].values / \
              train_sales.loc[(train_sales.regYear == 2017) & (train_sales.regMonth == 4), 'salesVolume'].values
    m17_1_5 = train_sales.loc[(train_sales.regYear == 2017) & (train_sales.regMonth == 1), 'salesVolume'].values / \
              train_sales.loc[(train_sales.regYear == 2017) & (train_sales.regMonth == 5), 'salesVolume'].values

    m17_2_3 = train_sales.loc[(train_sales.regYear == 2017) & (train_sales.regMonth == 2), 'salesVolume'].values / \
              train_sales.loc[(train_sales.regYear == 2017) & (train_sales.regMonth == 3), 'salesVolume'].values
    m17_2_4 = train_sales.loc[(train_sales.regYear == 2017) & (train_sales.regMonth == 2), 'salesVolume'].values / \
              train_sales.loc[(train_sales.regYear == 2017) & (train_sales.regMonth == 4), 'salesVolume'].values
    m17_2_5 = train_sales.loc[(train_sales.regYear == 2017) & (train_sales.regMonth == 2), 'salesVolume'].values / \
              train_sales.loc[(train_sales.regYear == 2017) & (train_sales.regMonth == 5), 'salesVolume'].values
    m17_2_6 = train_sales.loc[(train_sales.regYear == 2017) & (train_sales.regMonth == 2), 'salesVolume'].values / \
              train_sales.loc[(train_sales.regYear == 2017) & (train_sales.regMonth == 6), 'salesVolume'].values

    m17_3_4 = train_sales.loc[(train_sales.regYear == 2017) & (train_sales.regMonth == 3), 'salesVolume'].values / \
              train_sales.loc[(train_sales.regYear == 2017) & (train_sales.regMonth == 4), 'salesVolume'].values
    m17_3_5 = train_sales.loc[(train_sales.regYear == 2017) & (train_sales.regMonth == 3), 'salesVolume'].values / \
              train_sales.loc[(train_sales.regYear == 2017) & (train_sales.regMonth == 5), 'salesVolume'].values
    m17_3_6 = train_sales.loc[(train_sales.regYear == 2017) & (train_sales.regMonth == 3), 'salesVolume'].values / \
              train_sales.loc[(train_sales.regYear == 2017) & (train_sales.regMonth == 6), 'salesVolume'].values
    m17_3_7 = train_sales.loc[(train_sales.regYear == 2017) & (train_sales.regMonth == 3), 'salesVolume'].values / \
              train_sales.loc[(train_sales.regYear == 2017) & (train_sales.regMonth == 7), 'salesVolume'].values

    m16_1 = m16_1_2 / 2 + m16_1_3 / 4 + m16_1_4 / 8 + m16_1_5 / 8
    m16_2 = m16_2_3 / 2 + m16_2_4 / 4 + m16_2_5 / 8 + m16_2_6 / 8
    m16_3 = m16_3_4 / 2 + m16_3_5 / 4 + m16_3_6 / 8 + m16_3_7 / 8

    m17_1 = m17_1_2 / 2 + m17_1_3 / 4 + m17_1_4 / 8 + m17_1_5 / 8
    m17_2 = m17_2_3 / 2 + m17_2_4 / 4 + m17_2_5 / 8 + m17_2_6 / 8
    m17_3 = m17_3_4 / 2 + m17_3_5 / 4 + m17_3_6 / 8 + m17_3_7 / 8

    m1 = m16_1 * 0.4 + m17_1 * 0.6
    m2 = m16_2 * 0.4 + m17_2 * 0.6
    m3 = m16_3 * 0.4 + m17_3 * 0.6

    evaluation_public.loc[evaluation_public.regMonth == 2, 'forecastVolum'] = train_sales.loc[(train_sales.regYear == 2017) & (train_sales.regMonth == 1), 'salesVolume'].values / m1
    evaluation_public.loc[evaluation_public.regMonth == 3, 'forecastVolum'] = train_sales.loc[(train_sales.regYear == 2017) & (train_sales.regMonth == 2), 'salesVolume'].values / m2
    evaluation_public.loc[evaluation_public.regMonth == 4, 'forecastVolum'] = train_sales.loc[(train_sales.regYear == 2017) & (train_sales.regMonth == 3), 'salesVolume'].values / m3
    return evaluation_public

rule2=yulaorule(train_sales.copy())

In [21]:
rule2.head(10)

   id province  adcode             model  regYear  regMonth  forecastVolum
0   1       上海  310000  3c974920a76ac9c1     2018         1       9.312498
1   2       云南  530000  3c974920a76ac9c1     2018         1      12.045405
2   3      内蒙古  150000  3c974920a76ac9c1     2018         1       4.930692
3   4       北京  110000  3c974920a76ac9c1     2018         1       9.292539
4   5       四川  510000  3c974920a76ac9c1     2018         1      12.842968
5   6       安徽  340000  3c974920a76ac9c1     2018         1       6.194126
6   7       山东  370000  3c974920a76ac9c1     2018         1      14.105116
7   8       山西  140000  3c974920a76ac9c1     2018         1       6.675350
8   9       广东  440000  3c974920a76ac9c1     2018         1      76.486815
9  10       广西  450000  3c974920a76ac9c1     2018         1      11.187078

In [22]:
rule=rule2.merge(rule1,on=["adcode", "model", "province","regMonth"],how='left').rename(columns={'forecastVolum':'forecastVolum2'})
day_map = {1:31,2:28,3:31,4:30,5:31,6:30,7:31,8:31,9:30,10:31,11:30,12:31}
rule['daycount']=rule['regMonth'].map(day_map)
rule['forecastVolum']=(0.5*rule['forecastVolum2']+0.5*rule['forecastVolum1'])*rule['daycount']

In [23]:
rule.head(10)

,id,province,adcode,model,regYear,regMonth,forecastVolum2,bodyType,forecastVolum1,daycount,forecastVolum
0,1,上海,310000,3c974920a76ac9c1,2018,1,9.312498,SUV,10.388013,31,305.357927
1,2,云南,530000,3c974920a76ac9c1,2018,1,12.045405,SUV,13.650471,31,398.286085
2,3,内蒙古,150000,3c974920a76ac9c1,2018,1,4.930692,SUV,5.400057,31,160.126608
3,4,北京,110000,3c974920a76ac9c1,2018,1,9.292539,SUV,17.412660,31,413.930582
4,5,四川,510000,3c974920a76ac9c1,2018,1,12.842968,SUV,14.100386,31,417.621975
5,6,安徽,340000,3c974920a76ac9c1,2018,1,6.194126,SUV,6.080924,31,190.263283
6,7,山东,370000,3c974920a76ac9c1,2018,1,14.105116,SUV,15.800246,31,463.533112
7,8,山西,140000,3c974920a76ac9c1,2018,1,6.675350,SUV,8.491733,31,235.089794
8,9,广东,440000,3c974920a76ac9c1,2018,1,76.486815,SUV,95.108915,31,2659.733816
9,10,广西,450000,3c974920a76ac9c1,2018,1,11.187078,SUV,13.960963,31,389.794634

In [24]:
rule.shape

(5280, 11)

In [25]:
rule['forecastVolum'] = rule['forecastVolum'].apply(lambda x: 0 if x < 0 else int(round(x)))
rule[['id','forecastVolum']].to_csv('guize1_0901.csv',index=False)

In [31]:
rule1 = pd.read_csv("guize1_0901.csv")
rule1.head(2)

   id  forecastVolum
0   1            305
1   2            398

In [32]:
rule2 = pd.read_csv("guize2_0901.csv")
rule2.head(2)

   id  forecastVolum
0   1            273
1   2            357

In [33]:
rule1["forecastVolum"] = rule1["forecastVolum"]*0.5 +rule2["forecastVolum"]*0.5
rule1.head(2)

   id  forecastVolum
0   1          289.0
1   2          377.5

In [34]:
rule1['forecastVolum'] = rule1['forecastVolum'].apply(lambda x: 0 if x < 0 else int(round(x)))
rule1[['id','forecastVolum']].to_csv('rongheguize_0901.csv',index=False)