In [2]:
特征：
   'label','popularity','carCommentVolum','newsReplyVolum'平移了12个月
    train:
        1,  2,  3,  4,  5,  6,  7,  8,  9,  10,  11,  12
        13, 14, 15, 16, 17, 18, 19, 20, 21, 22,  23,  24 
        
    test: 21,22,23,24

SyntaxError: invalid character in identifier (<ipython-input-2-027fb5b461bb>, line 1)

In [1]:
# import sys
import numpy as np
import pandas as pd
# import os 
# import gc
from tqdm import tqdm, tqdm_notebook
from sklearn.model_selection import StratifiedKFold, KFold

from sklearn.metrics import f1_score, roc_auc_score
from sklearn.metrics import mean_squared_error as mse
from sklearn.preprocessing import LabelEncoder
import datetime
import time
import lightgbm as lgb
import xgboost as xgb
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
warnings.filterwarnings('ignore')
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [2]:
# path  = './ccf_car/'
train_sales  = pd.read_csv('train_sales_data.csv')


train_search = pd.read_csv('train_search_data.csv')
train_user   = pd.read_csv('train_user_reply_data.csv')
evaluation_public = pd.read_csv('evaluation_public.csv')
# submit_example    = pd.read_csv('submit_example.csv')
data = pd.concat([train_sales, evaluation_public], ignore_index=True)
data = data.merge(train_search, 'left', on=['province', 'adcode', 'model', 'regYear', 'regMonth'])
data = data.merge(train_user, 'left', on=['model', 'regYear', 'regMonth'])
data['label'] = data['salesVolume']
data['id'] = data['id'].fillna(0).astype(int)
data['bodyType'] = data['model'].map(train_sales.drop_duplicates('model').set_index('model')['bodyType'])
#索引-->value
#LabelEncoder
for i in ['bodyType', 'model']:
    data[i] = data[i].map(dict(zip(data[i].unique(), range(data[i].nunique()))))
    #key-->value
data['mt'] = (data['regYear'] - 2016) * 12 + data['regMonth']
initial_key_list = ['adcode','bodyType','forecastVolum','id','model','province','regMonth','regYear','salesVolume','popularity','carCommentVolum','newsReplyVolum'	,'label','mt']
data = data[initial_key_list].copy()


data.tail()

,adcode,bodyType,forecastVolum,id,model,province,regMonth,regYear,salesVolume,popularity,carCommentVolum,newsReplyVolum,label,mt
36955,350000,0,NaN,5364,59,福建,4,2018,NaN,NaN,NaN,NaN,NaN,28
36956,210000,0,NaN,5365,59,辽宁,4,2018,NaN,NaN,NaN,NaN,NaN,28
36957,500000,0,NaN,5366,59,重庆,4,2018,NaN,NaN,NaN,NaN,NaN,28
36958,610000,0,NaN,5367,59,陕西,4,2018,NaN,NaN,NaN,NaN,NaN,28
36959,230000,0,NaN,5368,59,黑龙江,4,2018,NaN,NaN,NaN,NaN,NaN,28

In [3]:
def windows_feature(data,judge):
    if (judge >1):
        print("windows_var_features start")
        del data['windows4_var'],data['windows5_var'],data['windows12_var'],data['model_adcode']
#         del data['ratio'],data['differ'],data['ratio2'],data['differ2']
        df = data.copy()
        df_all = pd.DataFrame()
        df['model_adcode'] = df['adcode'] + df['model']
        model_adcode = list(df.model_adcode.unique())
        for i in tqdm(model_adcode):
            idx = (df['model_adcode']==i)
            df2 = df[idx] 
#             df2['windows3_var'] = df2['label'].rolling(3).var()
            df2['windows4_var'] = df2['label'].rolling(4).var()
            df2['windows5_var'] = df2['label'].rolling(5).var()
          
            df2['windows12_var'] = df2['label'].rolling(12).var()
            
#             df2['windows3_std'] = df2['label'].rolling(3).std()
#             df2['windows4_std'] = df2['label'].rolling(2).mean()
#             df2['windows5_std'] = df2['label'].rolling(3).mean()
           
#             df2['windows12_std'] = df2['label'].rolling(4).mean()
            
#             df2['ratio'] = df2.groupby('model_adcode')['label'].apply(lambda x: x / x.shift(1)) #.apply(lambda x: x - x.shift(1)).reset_index()
#             df2['differ'] = df2.groupby('model_adcode')['label'].apply(lambda x: x - x.shift(1))
            
#             df2['ratio2'] = df2.groupby('model_adcode')['ratio'].apply(lambda x: x / x.shift(1)) #.apply(lambda x: x - x.shift(1)).reset_index()
#             df2['differ2'] = df2.groupby('model_adcode')['differ'].apply(lambda x: x - x.shift(1))
            
            df_all = pd.concat([df_all, df2], ignore_index=True)
        data = data.merge(df_all, 'left', on=['adcode','bodyType','forecastVolum','id','model','province','regMonth','regYear','salesVolume','popularity','carCommentVolum','newsReplyVolum','pred_label','label','mt'])
        print("windows_var_features end")
        return data
    else:
        print("windows_var_features start")
        df = data.copy()
        df_all = pd.DataFrame()
        df['model_adcode'] = df['adcode'] + df['model']
        model_adcode = list(df.model_adcode.unique())
        for i in tqdm(model_adcode):
            idx = (df['model_adcode']==i)
            df2 = df[idx]
            
#             df2['windows3_var'] = df2['label'].rolling(3).var()
            df2['windows4_var'] = df2['label'].rolling(4).var()
            df2['windows5_var'] = df2['label'].rolling(6).var()
            
            df2['windows12_var'] = df2['label'].rolling(12).var()
            
#             df2['windows3_std'] = df2['label'].rolling(3).std()
#             df2['windows4_std'] = df2['label'].rolling(2).mean()
#             df2['windows5_std'] = df2['label'].rolling(3).mean()
           
#             df2['windows12_std'] = df2['label'].rolling(4).mean()
            
#             df2['ratio'] = df2.groupby('model_adcode')['label'].apply(lambda x: x / x.shift(1)) #.apply(lambda x: x - x.shift(1)).reset_index()
#             df2['differ'] = df2.groupby('model_adcode')['label'].apply(lambda x: x - x.shift(1))
#             df2['ratio2'] = df2.groupby('model_adcode')['ratio'].apply(lambda x: x / x.shift(1)) #.apply(lambda x: x - x.shift(1)).reset_index()
#             df2['differ2'] = df2.groupby('model_adcode')['differ'].apply(lambda x: x - x.shift(1))

            df_all = pd.concat([df_all, df2], ignore_index=True)
        data = data.merge(df_all, 'left', on=['adcode','bodyType','forecastVolum','id','model','province','regMonth','regYear','salesVolume','popularity','carCommentVolum','newsReplyVolum','label','mt'])
        print("windows_var_features end")
        return data

In [4]:
def get_stat_feature(df_):   
    df = df_.copy()
    stat_feat = []
    df['model_adcode'] = df['adcode'] + df['model']
    df['model_adcode_mt'] = df['model_adcode'] * 100 + df['mt']
    for col in tqdm(['label','popularity']):#,'newsReplyVolum'
        # shift
        for i in [1,2,3,4,5,6,7,8,9,10,11,12]:
            stat_feat.append('shift_model_adcode_mt_{}_{}'.format(col,i))
            df['model_adcode_mt_{}_{}'.format(col,i)] = df['model_adcode_mt'] + i
            df_last = df[~df[col].isnull()].set_index('model_adcode_mt_{}_{}'.format(col,i))
            df['shift_model_adcode_mt_{}_{}'.format(col,i)] = df['model_adcode_mt'].map(df_last[col])
        for i in [1,2,3,4]:
            df["differ_{}_{}".format(col,i)] = df['{}'.format(col)] -df['shift_model_adcode_mt_{}_{}'.format(col,i)]
#             stat_feat.append("differ_{}_{}".format(col,i))
        df["differ2_{}_{}".format(col,1)] = df["differ_{}_{}".format(col,2)] - df["differ_{}_{}".format(col,1)]
        stat_feat.append("differ2_{}_{}".format(col,1))
        df["differ2_{}_{}".format(col,2)] = df["differ_{}_{}".format(col,3)] - df["differ_{}_{}".format(col,2)]
        stat_feat.append("differ2_{}_{}".format(col,2))
        df["differ2_{}_{}".format(col,3)] = df["differ_{}_{}".format(col,4)] - df["differ_{}_{}".format(col,3)]
        stat_feat.append("differ2_{}_{}".format(col,3))
    return df,stat_feat

In [6]:
def valid_score(data, pred='pred_label', label='label', group='model'):
    data['pred_label'] = data['pred_label'].apply(lambda x: 0 if x < 0 else x).round().astype(int)
    data_agg = data.groupby('model').agg({
        pred:  list,
        label: [list, 'mean']
    }).reset_index()
    data_agg.columns = ['_'.join(col).strip() for col in data_agg.columns]
    nrmse_score = []
    for raw in data_agg[['{0}_list'.format(pred), '{0}_list'.format(label), '{0}_mean'.format(label)]].values:
        nrmse_score.append(
            mse(raw[0], raw[1]) ** 0.5 / raw[2]
        )
    print(1 - np.mean(nrmse_score))
    return 1 - np.mean(nrmse_score)

In [7]:
def online_score(data, pred='pred_label', label='true_sales', group='model'):
    data['pred_label'] = data['pred_label'].apply(lambda x: 0 if x < 0 else x).round().astype(int)
    y = pd.read_csv("valid_data_y.csv")
    data = data.merge(y, 'left', on=['id'])
    data_agg = data.groupby('model').agg({
        pred:  list,
        label: [list, 'mean']
    }).reset_index()
    data_agg.columns = ['_'.join(col).strip() for col in data_agg.columns]
    nrmse_score = []
    for raw in data_agg[['{0}_list'.format(pred), '{0}_list'.format(label), '{0}_mean'.format(label)]].values:
        nrmse_score.append(
            mse(raw[0], raw[1]) ** 0.5 / raw[2]
        )
    print(1 - np.mean(nrmse_score))
    return 1 - np.mean(nrmse_score)

In [8]:
def get_model_type(train_x,train_y,valid_x,valid_y,m_type='lgb'):   
    if m_type == 'lgb':
        model = lgb.LGBMRegressor(
                                num_leaves=2**4-1, reg_alpha=0.25, reg_lambda=0.25, objective='mse',
                                max_depth=-1, learning_rate=0.01, min_child_samples=1, random_state=1024,
                                n_estimators=2000, subsample=0.9, colsample_bytree=0.7,
                                )
        model.fit(train_x, train_y, 
                  
              eval_set=[(train_x, train_y),(valid_x, valid_y)], 
              categorical_feature=cate_feat, 
              early_stopping_rounds=100, verbose=100)      
    elif m_type == 'xgb':
        model = xgb.XGBRegressor(
                                max_depth=5 , learning_rate=0.01, n_estimators=4000, 
                                objective='reg:gamma', tree_method = 'hist',subsample=0.9, 
                                colsample_bytree=0.7, min_child_samples=5,eval_metric = 'rmse' 
                                )
        model.fit(train_x, train_y, 
              eval_set=[(train_x, train_y),(valid_x, valid_y)], 
              early_stopping_rounds=100, verbose=100)   
    return model

In [9]:
def get_train_model(df_, m, m_type):
    df = df_.copy()
    # 数据集划分
    st = 9
    all_idx   = (df['mt'].between(st , m-1))
    train_idx = (df['mt'].between(st , m-5))
    valid_idx = (df['mt'].between(m-4, m-4))
    test_idx  = (df['mt'].between(m  , m  ))
    
    print('all_idx  :',st ,m-1)
    print('train_idx:',st ,m-5)
    print('valid_idx:',m-4,m-4)
    print('test_idx :',m  ,m  )  
    # 最终确认
    train_x = df[train_idx][features]
    train_y = df[train_idx]['label']
    valid_x = df[valid_idx][features]
    valid_y = df[valid_idx]['label']   
    # get model
    model = get_model_type(train_x,train_y,valid_x,valid_y,m_type)  
    # offline
    df['pred_label'] = model.predict(df[features])
    best_score = valid_score(df[valid_idx]) 
    # online
    if m_type == 'lgb':
        model.n_estimators = model.best_iteration_ + 100
        model.fit(df[all_idx][features], df[all_idx]['label'], categorical_feature=cate_feat)
    elif m_type == 'xgb':
        model.n_estimators = model.best_iteration + 100
        model.fit(df[all_idx][features], df[all_idx]['label'])
    df['forecastVolum'] = model.predict(df[features])
    print('valid mean:',df[valid_idx]['pred_label'].mean())
    print('true  mean:',df[valid_idx]['label'].mean())
    print('test  mean:',df[test_idx]['forecastVolum'].mean())
    # 阶段结果
    sub = df[test_idx][['id']]
    sub['forecastVolum'] = df[test_idx]['forecastVolum'].apply(lambda x: 0 if x < 0 else x).round().astype(int)
    print(sub.shape)
    return sub,df[valid_idx]['pred_label']

In [11]:
data = windows_feature(data,1)
#     data = windowsPop_feature(data,judge)
data_df, stat_feat = get_stat_feature(data)
data_df.head(20)

windows_var_features start

100%|██████████████████████████████████████████████████████████████████████████████| 1320/1320 [00:18<00:00, 72.68it/s]

windows_var_features end

100%|████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  2.07it/s]

,adcode,bodyType,forecastVolum,id,model,province,regMonth,regYear,salesVolume,popularity,carCommentVolum,newsReplyVolum,label,mt,model_adcode,windows4_var,windows5_var,windows12_var,model_adcode_mt,model_adcode_mt_label_1,shift_model_adcode_mt_label_1,model_adcode_mt_label_2,shift_model_adcode_mt_label_2,model_adcode_mt_label_3,shift_model_adcode_mt_label_3,model_adcode_mt_label_4,shift_model_adcode_mt_label_4,model_adcode_mt_label_5,shift_model_adcode_mt_label_5,model_adcode_mt_label_6,shift_model_adcode_mt_label_6,model_adcode_mt_label_7,shift_model_adcode_mt_label_7,model_adcode_mt_label_8,shift_model_adcode_mt_label_8,model_adcode_mt_label_9,shift_model_adcode_mt_label_9,model_adcode_mt_label_10,shift_model_adcode_mt_label_10,model_adcode_mt_label_11,shift_model_adcode_mt_label_11,model_adcode_mt_label_12,shift_model_adcode_mt_label_12,differ_label_1,differ_label_2,differ_label_3,differ_label_4,differ2_label_1,differ2_label_2,differ2_label_3,model_adcode_mt_popularity_1,shift_model_adcode_mt_popularity_1,model_adcode_mt_popularity_2,shift_model_adcode_mt_popularity_2,model_adcode_mt_popularity_3,shift_model_adcode_mt_popularity_3,model_adcode_mt_popularity_4,shift_model_adcode_mt_popularity_4,model_adcode_mt_popularity_5,shift_model_adcode_mt_popularity_5,model_adcode_mt_popularity_6,shift_model_adcode_mt_popularity_6,model_adcode_mt_popularity_7,shift_model_adcode_mt_popularity_7,model_adcode_mt_popularity_8,shift_model_adcode_mt_popularity_8,model_adcode_mt_popularity_9,shift_model_adcode_mt_popularity_9,model_adcode_mt_popularity_10,shift_model_adcode_mt_popularity_10,model_adcode_mt_popularity_11,shift_model_adcode_mt_popularity_11,model_adcode_mt_popularity_12,shift_model_adcode_mt_popularity_12,differ_popularity_1,differ_popularity_2,differ_popularity_3,differ_popularity_4,differ2_popularity_1,differ2_popularity_2,differ2_popularity_3
0,310000,0,NaN,0,0,上海,1,2016,292.0,1479.0,11.0,106.0,292.0,1,310000,NaN,NaN,NaN,31000001,31000002,NaN,31000003,NaN,31000004,NaN,31000005,NaN,31000006,NaN,31000007,NaN,31000008,NaN,31000009,NaN,31000010,NaN,31000011,NaN,31000012,NaN,31000013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31000002,NaN,31000003,NaN,31000004,NaN,31000005,NaN,31000006,NaN,31000007,NaN,31000008,NaN,31000009,NaN,31000010,NaN,31000011,NaN,31000012,NaN,31000013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,530000,0,NaN,0,0,云南,1,2016,466.0,1594.0,11.0,106.0,466.0,1,530000,NaN,NaN,NaN,53000001,53000002,NaN,53000003,NaN,53000004,NaN,53000005,NaN,53000006,NaN,53000007,NaN,53000008,NaN,53000009,NaN,53000010,NaN,53000011,NaN,53000012,NaN,53000013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,53000002,NaN,53000003,NaN,53000004,NaN,53000005,NaN,53000006,NaN,53000007,NaN,53000008,NaN,53000009,NaN,53000010,NaN,53000011,NaN,53000012,NaN,53000013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,150000,0,NaN,0,0,内蒙古,1,2016,257.0,1479.0,11.0,106.0,257.0,1,150000,NaN,NaN,NaN,15000001,15000002,NaN,15000003,NaN,15000004,NaN,15000005,NaN,15000006,NaN,15000007,NaN,15000008,NaN,15000009,NaN,15000010,NaN,15000011,NaN,15000012,NaN,15000013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15000002,NaN,15000003,NaN,15000004,NaN,15000005,NaN,15000006,NaN,15000007,NaN,15000008,NaN,15000009,NaN,15000010,NaN,15000011,NaN,15000012,NaN,15000013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,110000,0,NaN,0,0,北京,1,2016,408.0,2370.0,11.0,106.0,408.0,1,110000,NaN,NaN,NaN,11000001,11000002,NaN,11000003,NaN,11000004,NaN,11000005,NaN,11000006,NaN,11000007,NaN,11000008,NaN,11000009,NaN,11000010,NaN,11000011,NaN,11000012,NaN,11000013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11000002,NaN,11000003,NaN,11000004,NaN,11000005,NaN,11000006,NaN,11000007,NaN,11000008,NaN,11000009,NaN,11000010,NaN,11000011,NaN,11000012,NaN,11000013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,510000,0,NaN,0,0,四川,1,2016,610.0,3562.0,11.0,106.0,610.0,1,510000,NaN,NaN,NaN,51000001,51000002,NaN,51000003,NaN,51000004,NaN,51000005,NaN,51000006,NaN,51000007,NaN,51000008,NaN,51000009,NaN,51000010,NaN,51000011,NaN,51000012,NaN,51000013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51000002,NaN,51000003,NaN,51000004,NaN,51000005,NaN,51000006,NaN,51000007,NaN,51000008,NaN,51000009,NaN,51000010,NaN,51000011,NaN,51000012,NaN,51000013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,340000,0,NaN,0,0,安徽,1,2016,206.0,1314.0,11.0,106.0,206.0,1,340000,NaN,NaN,NaN,34000001,34000002,NaN,34000003,NaN,34000004,NaN,34000005,NaN,34000006,NaN,34000007,NaN,34000008,NaN,34000009,NaN,34000010,NaN,34000011,NaN,34000012,NaN,34000013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,34000002,NaN,34000003,NaN,34000004,NaN,34000005,NaN,34000006,NaN,34000007,NaN,34000008,NaN,34000009,NaN,34000010,NaN,34000011,NaN,34000012,NaN,34000013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,370000,0,NaN,0,0,山东,1,2016,503.0,3476.0,11.0,106.0,503.0,1,370000,NaN,NaN,NaN,37000001,37000002,NaN,37000003,NaN,37000004,NaN,37000005,NaN,37000006,NaN,37000007,NaN,37000008,NaN,37000009,NaN,37000010,NaN,37000011,NaN,37000012,NaN,37000013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37000002,NaN,37000003,NaN,37000004,NaN,37000005,NaN,37000006,NaN,37000007,NaN,37000008,NaN,37000009,NaN,37000010,NaN,37000011,NaN,37000012,NaN,37000013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,140000,0,NaN,0,0,山西,1,2016,236.0,1422.0,11.0,106.0,236.0,1,140000,NaN,NaN,NaN,14000001,14000002,NaN,14000003,NaN,14000004,NaN,14000005,NaN,14000006,NaN,14000007,NaN,14000008,NaN,14000009,NaN,14000010,NaN,14000011,NaN,14000012,NaN,14000013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14000002,NaN,14000003,NaN,14000004,NaN,14000005,NaN,14000006,NaN,14000007,NaN,14000008,NaN,14000009,NaN,14000010,NaN,14000011,NaN,14000012,NaN,14000013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,440000,0,NaN,0,0,广东,1,2016,3635.0,7182.0,11.0,106.0,3635.0,1,440000,NaN,NaN,NaN,44000001,44000002,NaN,44000003,NaN,44000004,NaN,44000005,NaN,44000006,NaN,44000007,NaN,44000008,NaN,44000009,NaN,44000010,NaN,44000011,NaN,44000012,NaN,44000013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,44000002,NaN,44000003,NaN,44000004,NaN,44000005,NaN,44000006,NaN,44000007,NaN,44000008,NaN,44000009,NaN,44000010,NaN,44000011,NaN,44000012,NaN,44000013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,450000,0,NaN,0,0,广西,1,2016,450.0,1163.0,11.0,106.0,450.0,1,450000,NaN,NaN,NaN,45000001,45000002,NaN,45000003,NaN,45000004,NaN,45000005,NaN,45000006,NaN,45000007,NaN,45000008,NaN,45000009,NaN,45000010,NaN,45000011,NaN,45000012,NaN,45000013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45000002,NaN,45000003,NaN,45000004,NaN,45000005,NaN,45000006,NaN,45000007,NaN,45000008,NaN,45000009,NaN,45000010,NaN,45000011,NaN,45000012,NaN,45000013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,320000,0,NaN,0,0,江苏,1,2016,876.0,3670.0,11.0,106.0,876.0,1,320000,NaN,NaN,NaN,32000001,32000002,NaN,32000003,NaN,32000004,NaN,32000005,NaN,32000006,NaN,32000007,NaN,32000008,NaN,32000009,NaN,32000010,NaN,32000011,NaN,32000012,NaN,32000013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32000002,NaN,32000003,NaN,32000004,NaN,32000005,NaN,32000006,NaN,32000007,NaN,32000008,NaN,32000009,NaN,32000010,NaN,32000011,NaN,32000012,NaN,32000013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,360000,0,NaN,0,0,江西,1,2016,253.0,926.0,11.0,106.0,253.0,1,360000,NaN,NaN,NaN,36000001,36000002,NaN,36000003,NaN,36000004,NaN,36000005,NaN,36000006,NaN,36000007,NaN,36000008,NaN,36000009,NaN,36000010,NaN,36000011,NaN,36000012,NaN,36000013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36000002,NaN,36000003,NaN,36000004,NaN,36000005,NaN,36000006,NaN,36000007,NaN,36000008,NaN,36000009,NaN,36000010,NaN,36000011,NaN,36000012,NaN,36000013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,130000,0,NaN,0,0,河北,1,2016,306.0,2973.0,11.0,106.0,306.0,1,130000,NaN,NaN,NaN,13000001,13000002,NaN,13000003,NaN,13000004,NaN,13000005,NaN,13000006,NaN,13000007,NaN,13000008,NaN,13000009,NaN,13000010,NaN,13000011,NaN,13000012,NaN,13000013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13000002,NaN,13000003,NaN,13000004,NaN,13000005,NaN,13000006,NaN,13000007,NaN,13000008,NaN,13000009,NaN,13000010,NaN,13000011,NaN,13000012,NaN,13000013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,410000,0,NaN,0,0,河南,1,2016,537.0,3483.0,11.0,106.0,537.0,1,410000,NaN,NaN,NaN,41000001,41000002,NaN,41000003,NaN,41000004,NaN,41000005,NaN,41000006,NaN,41000007,NaN,41000008,NaN,41000009,NaN,41000010,NaN,41000011,NaN,41000012,NaN,41000013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,41000002,NaN,41000003,NaN,41000004,NaN,41000005,NaN,41000006,NaN,41000007,NaN,41000008,NaN,41000009,NaN,41000010,NaN,41000011,NaN,41000012,NaN,41000013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,330000,0,NaN,0,0,浙江,1,2016,650.0,3167.0,11.0,106.0,650.0,1,330000,NaN,NaN,NaN,33000001,33000002,NaN,33000003,NaN,33000004,NaN,33000005,NaN,33000006,NaN,33000007,NaN,33000008,NaN,33000009,NaN,33000010,NaN,33000011,NaN,33000012,NaN,33000013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33000002,NaN,33000003,NaN,33000004,NaN,33000005,NaN,33000006,NaN,33000007,NaN,33000008,NaN,33000009,NaN,33000010,NaN,33000011,NaN,33000012,NaN,33000013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,420000,0,NaN,0,0,湖北,1,2016,635.0,2190.0,11.0,106.0,635.0,1,420000,NaN,NaN,NaN,42000001,42000002,NaN,42000003,NaN,42000004,NaN,42000005,NaN,42000006,NaN,42000007,NaN,42000008,NaN,42000009,NaN,42000010,NaN,42000011,NaN,42000012,NaN,42000013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,42000002,NaN,42000003,NaN,42000004,NaN,42000005,NaN,42000006,NaN,42000007,NaN,42000008,NaN,42000009,NaN,42000010,NaN,42000011,NaN,42000012,NaN,42000013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,430000,0,NaN,0,0,湖南,1,2016,525.0,1666.0,11.0,106.0,525.0,1,430000,NaN,NaN,NaN,43000001,43000002,NaN,43000003,NaN,43000004,NaN,43000005,NaN,43000006,NaN,43000007,NaN,43000008,NaN,43000009,NaN,43000010,NaN,43000011,NaN,43000012,NaN,43000013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,43000002,NaN,43000003,NaN,43000004,NaN,43000005,NaN,43000006,NaN,43000007,NaN,43000008,NaN,43000009,NaN,43000010,NaN,43000011,NaN,43000012,NaN,43000013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,350000,0,NaN,0,0,福建,1,2016,462.0,1357.0,11.0,106.0,462.0,1,350000,NaN,NaN,NaN,35000001,35000002,NaN,35000003,NaN,35000004,NaN,35000005,NaN,35000006,NaN,35000007,NaN,35000008,NaN,35000009,NaN,35000010,NaN,35000011,NaN,35000012,NaN,35000013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35000002,NaN,35000003,NaN,35000004,NaN,35000005,NaN,35000006,NaN,35000007,NaN,35000008,NaN,35000009,NaN,35000010,NaN,35000011,NaN,35000012,NaN,35000013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,210000,0,NaN,0,0,辽宁,1,2016,791.0,2808.0,11.0,106.0,791.0,1,210000,NaN,NaN,NaN,21000001,21000002,NaN,21000003,NaN,21000004,NaN,21000005,NaN,21000006,NaN,21000007,NaN,21000008,NaN,21000009,NaN,21000010,NaN,21000011,NaN,21000012,NaN,21000013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21000002,NaN,21000003,NaN,21000004,NaN,21000005,NaN,21000006,NaN,21000007,NaN,21000008,NaN,21000009,NaN,21000010,NaN,21000011,NaN,21000012,NaN,21000013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,500000,0,NaN,0,0,重庆,1,2016,195.0,682.0,11.0,106.0,195.0,1,500000,NaN,NaN,NaN,50000001,50000002,NaN,50000003,NaN,50000004,NaN,50000005,NaN,50000006,NaN,50000007,NaN,50000008,NaN,50000009,NaN,50000010,NaN,50000011,NaN,50000012,NaN,50000013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50000002,NaN,50000003,NaN,50000004,NaN,50000005,NaN,50000006,NaN,50000007,NaN,50000008,NaN,50000009,NaN,50000010,NaN,50000011,NaN,50000012,NaN,50000013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
data_df.to_csv('nn_all_data.csv', index=False)

In [9]:
for month in [25,26,27,28]: 
    judge = month-24
    m_type = 'lgb' 
    data = windows_feature(data,judge)
#     data = windowsPop_feature(data,judge)
    data_df, stat_feat = get_stat_feature(data)
    
    win_feat = ['windows4_var','windows5_var','windows12_var']
#     winPop_feat = ['windowsPop4_var','windowsPop4_std','windowsPop5_var','windowsPop5_std','windowsPop12_var','windowsPop12_std']
#     ,'windows6_var','windows6_std']
#     qushi_feat = ['ratio2','differ2']
    num_feat = ['regYear','regMonth'] + stat_feat +win_feat#,'windows_var','windows_std'
    cate_feat = ['adcode','bodyType','model']

    if m_type == 'lgb':
        for i in cate_feat:
            data_df[i] = data_df[i].astype('category')
    elif m_type == 'xgb':
        lbl = LabelEncoder()  
        for i in tqdm(cate_feat):
            data_df[i] = lbl.fit_transform(data_df[i].astype(str))

    features = num_feat + cate_feat
    print(len(features), len(set(features)))
    sub,val_pred = get_train_model(data_df, month, m_type)
#     online_test_idx  = (data_df['mt'].between(21  , 24  ))
    print("---")
    print(data.loc[(data.regMonth==month)].shape)
    data.loc[(data.mt==month), 'salesVolume'   ] = sub['forecastVolum'].values
    data.loc[(data.mt==(month)), 'label'      ] = sub['forecastVolum'].values
    data.loc[(data.mt==(month)), 'pred_label'      ] = sub['forecastVolum'].values
#     data['n_label'] = data['label'] / data['model_weight']



    # # sub = data.loc[(data.regMonth>=1)&(data.regYear==2018), ['id','salesVolume']]
# # sub.columns = ['id','forecastVolum']
# # sub[['id','forecastVolum']].round().astype(int).to_csv('submit/yulao_lgb.csv', index=False)
# best_score = online_score(data[online_test_idx])

windows_var_features start

100%|██████████████████████████████████████████████████████████████████████████████| 1320/1320 [00:17<00:00, 49.92it/s]

windows_var_features end

100%|████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  2.18it/s]

38 38
all_idx  : 9 24
train_idx: 9 20
valid_idx: 21 21
test_idx : 25 25
Training until validation scores don't improve for 100 rounds.
[100]	training's l2: 127571	valid_1's l2: 142191
[200]	training's l2: 44834.2	valid_1's l2: 55322.5
[300]	training's l2: 26537.8	valid_1's l2: 37167
[400]	training's l2: 20077.8	valid_1's l2: 31777
[500]	training's l2: 16201.8	valid_1's l2: 29034
[600]	training's l2: 13827.3	valid_1's l2: 27644.4
[700]	training's l2: 12245.8	valid_1's l2: 26524.7
[800]	training's l2: 11004.9	valid_1's l2: 25753.1
[900]	training's l2: 9996.8	valid_1's l2: 25365.4
[1000]	training's l2: 9162.67	valid_1's l2: 25175.6
[1100]	training's l2: 8446.73	valid_1's l2: 25001.8
[1200]	training's l2: 7845.25	valid_1's l2: 24789.7
[1300]	training's l2: 7331.46	valid_1's l2: 24663.4
[1400]	training's l2: 6900.68	valid_1's l2: 24512.2
[1500]	training's l2: 6515.77	valid_1's l2: 24326.4
[1600]	training's l2: 6161.57	valid_1's l2: 24250.5
[1700]	training's l2: 5838.37	valid_1's l2: 24117.8
[1800]	training's l2: 5541.19	valid_1's l2: 24003.3
[1900]	training's l2: 5260.46	valid_1's l2: 23900.1
[2000]	training's l2: 5010.02	valid_1's l2: 23781.8
Did not meet early stopping. Best iteration is:
[2000]	training's l2: 5010.02	valid_1's l2: 23781.8
0.8172470632539641
valid mean: 631.4777607672443
true  mean: 649.3121212121212
test  mean: 490.62419589651904
(1320, 2)
---
(0, 18)
windows_var_features start

100%|██████████████████████████████████████████████████████████████████████████████| 1320/1320 [00:19<00:00, 66.89it/s]

windows_var_features end

100%|████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  2.11it/s]

38 38
all_idx  : 9 25
train_idx: 9 21
valid_idx: 22 22
test_idx : 26 26
Training until validation scores don't improve for 100 rounds.
[100]	training's l2: 127727	valid_1's l2: 107596
[200]	training's l2: 44762.5	valid_1's l2: 42542.2
[300]	training's l2: 26509.3	valid_1's l2: 35178.9
[400]	training's l2: 19979.5	valid_1's l2: 35735.4
Early stopping, best iteration is:
[329]	training's l2: 24111.9	valid_1's l2: 35024
0.7251803061393753
valid mean: 640.3134913534286
true  mean: 616.5537878787878
test  mean: 368.29292823743816
(1320, 2)
---
(0, 19)
windows_var_features start

100%|██████████████████████████████████████████████████████████████████████████████| 1320/1320 [00:19<00:00, 47.78it/s]

windows_var_features end

100%|████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  2.04it/s]

38 38
all_idx  : 9 26
train_idx: 9 22
valid_idx: 23 23
test_idx : 27 27
Training until validation scores don't improve for 100 rounds.
[100]	training's l2: 128116	valid_1's l2: 114164
[200]	training's l2: 44973.4	valid_1's l2: 33355.1
[300]	training's l2: 26976.4	valid_1's l2: 23195.7
[400]	training's l2: 20818.5	valid_1's l2: 23065.7
Early stopping, best iteration is:
[336]	training's l2: 24162.9	valid_1's l2: 22828.9
0.7905562011237878
valid mean: 671.3575822749254
true  mean: 673.0143939393939
test  mean: 438.8058862644233
(1320, 2)
---
(0, 19)
windows_var_features start

100%|██████████████████████████████████████████████████████████████████████████████| 1320/1320 [00:19<00:00, 68.14it/s]

windows_var_features end

100%|████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  2.08it/s]

38 38
all_idx  : 9 27
train_idx: 9 23
valid_idx: 24 24
test_idx : 28 28
Training until validation scores don't improve for 100 rounds.
[100]	training's l2: 128256	valid_1's l2: 470990
[200]	training's l2: 44693.4	valid_1's l2: 219875
[300]	training's l2: 26896.8	valid_1's l2: 146865
[400]	training's l2: 20753.1	valid_1's l2: 118112
[500]	training's l2: 16993.2	valid_1's l2: 102822
[600]	training's l2: 14623.2	valid_1's l2: 96304.4
[700]	training's l2: 13166.5	valid_1's l2: 93379.3
[800]	training's l2: 12067	valid_1's l2: 92097.4
[900]	training's l2: 11091.4	valid_1's l2: 91777.1
[1000]	training's l2: 10258.2	valid_1's l2: 90852.7
[1100]	training's l2: 9494.87	valid_1's l2: 89772.4
[1200]	training's l2: 8850.81	valid_1's l2: 88885.9
[1300]	training's l2: 8303.51	valid_1's l2: 88344.6
[1400]	training's l2: 7812.56	valid_1's l2: 87999.4
[1500]	training's l2: 7351.36	valid_1's l2: 87537
[1600]	training's l2: 6955.18	valid_1's l2: 86987.5
[1700]	training's l2: 6622.99	valid_1's l2: 86612
[1800]	training's l2: 6314.8	valid_1's l2: 86456.7
[1900]	training's l2: 6052.5	valid_1's l2: 86185.6
[2000]	training's l2: 5798.54	valid_1's l2: 85936.8
Did not meet early stopping. Best iteration is:
[2000]	training's l2: 5798.54	valid_1's l2: 85936.8
0.7789236346640822
valid mean: 817.5801648520662
true  mean: 899.8204545454546
test  mean: 425.8026335934632
(1320, 2)
---
(0, 19)

In [10]:
sub = data.loc[(data.regMonth>=1)&(data.regYear==2018), ['id','salesVolume']]
sub.columns = ['id','forecastVolum']
sub.head()

       id  forecastVolum
31680   1          269.0
31681   2          309.0
31682   3          153.0
31683   4          274.0
31684   5          351.0

In [12]:
sub[['id','forecastVolum']].round().astype(int).to_csv('submit/lgb0922.csv', index=False)

In [10]:
for month in [21,22,23,24]: 
    m_type = 'xgb' 
    judge = month-20
    data = windows_feature(data,judge)
    
    data_df, stat_feat = get_stat_feature(data)
    
    win_feat = ['windows4_var','windows4_std','windows5_var','windows5_std','windows12_var','windows12_std']
#     ,'windows6_var','windows6_std']
#     qushi_feat = ['ratio2','differ2']
    num_feat = ['regYear','regMonth'] + stat_feat +win_feat#,'windows_var','windows_std'
    cate_feat = ['adcode','bodyType','model']
    
    if m_type == 'lgb':
        for i in cate_feat:
            data_df[i] = data_df[i].astype('category')
    elif m_type == 'xgb':
        lbl = LabelEncoder()  
        for i in tqdm(cate_feat):
            data_df[i] = lbl.fit_transform(data_df[i].astype(str))
           
    features = num_feat + cate_feat
    print(len(features), len(set(features)))   
    
    sub,val_pred = get_train_model(data_df, month, m_type)   
    online_test_idx  = (data_df['mt'].between(21  , 24  ))
    print("---")
    print(data.loc[(data.regMonth==month)].shape)
    data.loc[(data.mt==month), 'salesVolume'   ] = sub['forecastVolum'].values
    data.loc[(data.mt==(month)), 'label'      ] = sub['forecastVolum'].values
    data.loc[(data.mt==(month)), 'pred_label'      ] = sub['forecastVolum'].values


    # # sub = data.loc[(data.regMonth>=1)&(data.regYear==2018), ['id','salesVolume']]
# # sub.columns = ['id','forecastVolum']
# # sub[['id','forecastVolum']].round().astype(int).to_csv('submit/yulao_lgb.csv', index=False)
best_score = online_score(data[online_test_idx])

windows_var_features start

100%|██████████████████████████████████████████████████████████████████████████████| 1320/1320 [00:25<00:00, 52.35it/s]

windows_var_features end

100%|████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.66it/s]
100%|████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 28.65it/s]

37 37
all_idx  : 5 20
train_idx: 5 16
valid_idx: 17 17
test_idx : 21 21

KeyError: "['windows4_std', 'windows5_std', 'windows12_var', 'windows12_std', 'windows4_var', 'windows5_var'] not in index"

In [14]:
for month in [21,22,23,24]: 
    m_type = 'xgb' 
    
    data_df, stat_feat = get_stat_feature(data)
    
    win_feat = ['windows4_var','windows4_std','windows5_var','windows5_std','windows6_var','windows6_std']
#     qushi_feat = ['ratio2','differ2']
    num_feat = ['regYear','regMonth'] + stat_feat +win_feat#,'windows_var','windows_std'
    cate_feat = ['adcode','bodyType','model']
    
    if m_type == 'lgb':
        for i in cate_feat:
            data_df[i] = data_df[i].astype('category')
    elif m_type == 'xgb':
        lbl = LabelEncoder()  
        for i in tqdm(cate_feat):
            data_df[i] = lbl.fit_transform(data_df[i].astype(str))
           
    features = num_feat + cate_feat
    print(len(features), len(set(features)))   
    
    sub,val_pred = get_train_model(data_df, month, m_type)   
    data.loc[(data.regMonth==(month-24))&(data.regYear==2018), 'salesVolume'] = sub['forecastVolum'].values
    data.loc[(data.regMonth==(month-24))&(data.regYear==2018), 'label'      ] = sub['forecastVolum'].values	
sub = data.loc[(data.regMonth>=1)&(data.regYear==2018), ['id','salesVolume']]
sub.columns = ['id','forecastVolum']
sub[['id','forecastVolum']].round().astype(int).to_csv('submit/yulao_xgb.csv', index=False)

100%|████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:05<00:00,  1.42s/it]
100%|████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 15.10it/s]

53 53
all_idx  : 13 24
train_idx: 13 20
valid_idx: 21 21
test_idx : 25 25
[0]	validation_0-rmse:841.387	validation_1-rmse:1046.81
Multiple eval metrics have been passed: 'validation_1-rmse' will be used for early stopping.

Will train until validation_1-rmse hasn't improved in 100 rounds.
[100]	validation_0-rmse:840.854	validation_1-rmse:1046.28
[200]	validation_0-rmse:839.416	validation_1-rmse:1044.83
[300]	validation_0-rmse:835.586	validation_1-rmse:1040.97
[400]	validation_0-rmse:825.694	validation_1-rmse:1030.91
[500]	validation_0-rmse:801.738	validation_1-rmse:1006.18
[600]	validation_0-rmse:750.162	validation_1-rmse:951.587
[700]	validation_0-rmse:657.192	validation_1-rmse:849.31
[800]	validation_0-rmse:524.723	validation_1-rmse:696.311
[900]	validation_0-rmse:380.162	validation_1-rmse:522.151
[1000]	validation_0-rmse:259.234	validation_1-rmse:376.202
[1100]	validation_0-rmse:179.886	validation_1-rmse:282.214
[1200]	validation_0-rmse:145.639	validation_1-rmse:248.148
[1300]	validation_0-rmse:132.764	validation_1-rmse:236.328
[1400]	validation_0-rmse:123.956	validation_1-rmse:229.286
[1500]	validation_0-rmse:117.525	validation_1-rmse:225.476
[1600]	validation_0-rmse:112.077	validation_1-rmse:222.002
[1700]	validation_0-rmse:108.012	validation_1-rmse:219.62
[1800]	validation_0-rmse:105.329	validation_1-rmse:218.541
[1900]	validation_0-rmse:102.6	validation_1-rmse:216.826
[2000]	validation_0-rmse:100.224	validation_1-rmse:215.662
[2100]	validation_0-rmse:98.22	validation_1-rmse:215.319
[2200]	validation_0-rmse:96.532	validation_1-rmse:215.243
[2300]	validation_0-rmse:95.2175	validation_1-rmse:214.773
[2400]	validation_0-rmse:93.5902	validation_1-rmse:213.994
[2500]	validation_0-rmse:92.0521	validation_1-rmse:213.366
[2600]	validation_0-rmse:90.7138	validation_1-rmse:212.787
[2700]	validation_0-rmse:89.3237	validation_1-rmse:212.099
[2800]	validation_0-rmse:88.0724	validation_1-rmse:211.505
[2900]	validation_0-rmse:86.8326	validation_1-rmse:211.486
[3000]	validation_0-rmse:85.4657	validation_1-rmse:210.631
[3100]	validation_0-rmse:84.0276	validation_1-rmse:210.01
[3200]	validation_0-rmse:82.8386	validation_1-rmse:209.758
[3300]	validation_0-rmse:81.721	validation_1-rmse:209.527
[3400]	validation_0-rmse:80.6025	validation_1-rmse:209.511
[3500]	validation_0-rmse:79.6226	validation_1-rmse:208.998
[3600]	validation_0-rmse:78.5413	validation_1-rmse:208.909
[3700]	validation_0-rmse:77.562	validation_1-rmse:208.716
[3800]	validation_0-rmse:76.4457	validation_1-rmse:208.448
[3900]	validation_0-rmse:75.3537	validation_1-rmse:208.069
[3999]	validation_0-rmse:74.4427	validation_1-rmse:208.153
0.7704167529810075
valid mean: 623.15094
true  mean: 649.3121212121212
test  mean: 458.79114

100%|████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:05<00:00,  1.34s/it]
100%|████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 12.25it/s]

53 53
all_idx  : 13 25
train_idx: 13 21
valid_idx: 22 22
test_idx : 26 26
[0]	validation_0-rmse:866.621	validation_1-rmse:1007.38
Multiple eval metrics have been passed: 'validation_1-rmse' will be used for early stopping.

Will train until validation_1-rmse hasn't improved in 100 rounds.
[100]	validation_0-rmse:866.089	validation_1-rmse:1006.85
[200]	validation_0-rmse:864.653	validation_1-rmse:1005.43
[300]	validation_0-rmse:860.828	validation_1-rmse:1001.62
[400]	validation_0-rmse:850.935	validation_1-rmse:991.753
[500]	validation_0-rmse:826.915	validation_1-rmse:967.795
[600]	validation_0-rmse:774.935	validation_1-rmse:915.746
[700]	validation_0-rmse:680.726	validation_1-rmse:819.708
[800]	validation_0-rmse:544.976	validation_1-rmse:682.224
[900]	validation_0-rmse:395.274	validation_1-rmse:534.143
[1000]	validation_0-rmse:268.46	validation_1-rmse:413.542
[1100]	validation_0-rmse:185.094	validation_1-rmse:338.885
[1200]	validation_0-rmse:148.412	validation_1-rmse:310.795
[1300]	validation_0-rmse:135.604	validation_1-rmse:305.034
[1400]	validation_0-rmse:127.006	validation_1-rmse:301.104
[1500]	validation_0-rmse:120.891	validation_1-rmse:300.462
Stopping. Best iteration:
[1438]	validation_0-rmse:124.346	validation_1-rmse:300.103

0.6135062378600542
valid mean: 455.9764
true  mean: 616.5537878787878
test  mean: 287.6134

100%|████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:05<00:00,  1.28s/it]
100%|████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 11.60it/s]

53 53
all_idx  : 13 26
train_idx: 13 22
valid_idx: 23 23
test_idx : 27 27
[0]	validation_0-rmse:881.709	validation_1-rmse:1071.9
Multiple eval metrics have been passed: 'validation_1-rmse' will be used for early stopping.

Will train until validation_1-rmse hasn't improved in 100 rounds.
[100]	validation_0-rmse:881.177	validation_1-rmse:1071.36
[200]	validation_0-rmse:879.744	validation_1-rmse:1069.89
[300]	validation_0-rmse:875.924	validation_1-rmse:1065.98
[400]	validation_0-rmse:866.039	validation_1-rmse:1055.8
[500]	validation_0-rmse:842.007	validation_1-rmse:1030.84
[600]	validation_0-rmse:789.895	validation_1-rmse:975.336
[700]	validation_0-rmse:694.969	validation_1-rmse:871.571
[800]	validation_0-rmse:557.798	validation_1-rmse:716.699
[900]	validation_0-rmse:405.58	validation_1-rmse:542.434
[1000]	validation_0-rmse:276.35	validation_1-rmse:397.253
[1100]	validation_0-rmse:190.667	validation_1-rmse:305.207
[1200]	validation_0-rmse:154.971	validation_1-rmse:271.795
[1300]	validation_0-rmse:140.976	validation_1-rmse:261.29
[1400]	validation_0-rmse:131.097	validation_1-rmse:253.97
[1500]	validation_0-rmse:123.573	validation_1-rmse:249.8
[1600]	validation_0-rmse:117.466	validation_1-rmse:246.017
[1700]	validation_0-rmse:113.772	validation_1-rmse:243.643
[1800]	validation_0-rmse:110.041	validation_1-rmse:242.037
[1900]	validation_0-rmse:106.974	validation_1-rmse:240.72
[2000]	validation_0-rmse:104.46	validation_1-rmse:240.411
[2100]	validation_0-rmse:102.371	validation_1-rmse:240.26
[2200]	validation_0-rmse:100.264	validation_1-rmse:239.565
[2300]	validation_0-rmse:98.5715	validation_1-rmse:239.589
[2400]	validation_0-rmse:97.1418	validation_1-rmse:239.243
[2500]	validation_0-rmse:95.5244	validation_1-rmse:238.933
[2600]	validation_0-rmse:94.227	validation_1-rmse:238.502
[2700]	validation_0-rmse:92.788	validation_1-rmse:238.087
Stopping. Best iteration:
[2684]	validation_0-rmse:93.0052	validation_1-rmse:237.949

0.7218989650293122
valid mean: 568.9693
true  mean: 673.0143939393939
test  mean: 337.8751

100%|████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:05<00:00,  1.29s/it]
100%|████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 11.90it/s]

53 53
all_idx  : 13 27
train_idx: 13 23
valid_idx: 24 24
test_idx : 28 28
[0]	validation_0-rmse:900.66	validation_1-rmse:1451.31
Multiple eval metrics have been passed: 'validation_1-rmse' will be used for early stopping.

Will train until validation_1-rmse hasn't improved in 100 rounds.
[100]	validation_0-rmse:900.128	validation_1-rmse:1450.78
[200]	validation_0-rmse:898.694	validation_1-rmse:1449.33
[300]	validation_0-rmse:894.87	validation_1-rmse:1445.44
[400]	validation_0-rmse:884.963	validation_1-rmse:1435.29
[500]	validation_0-rmse:860.829	validation_1-rmse:1410.04
[600]	validation_0-rmse:808.295	validation_1-rmse:1353.21
[700]	validation_0-rmse:712.128	validation_1-rmse:1245.94
[800]	validation_0-rmse:572.214	validation_1-rmse:1087.8
[900]	validation_0-rmse:415.731	validation_1-rmse:924.84
[1000]	validation_0-rmse:282.041	validation_1-rmse:806.888
[1100]	validation_0-rmse:193.642	validation_1-rmse:738.259
[1200]	validation_0-rmse:155.982	validation_1-rmse:712.916
[1300]	validation_0-rmse:143.821	validation_1-rmse:711.15
Stopping. Best iteration:
[1263]	validation_0-rmse:147.131	validation_1-rmse:709.407

0.41897786888760846
valid mean: 498.20517
true  mean: 899.8204545454546
test  mean: 324.48294

In [113]:
for month in [21,22,23,24]: 
    m_type = 'lgb' 
    
    data_df, stat_feat = get_stat_feature(data)
    
    num_feat = ['regYear','regMonth'] + stat_feat
    cate_feat = ['adcode','bodyType','model']
    
    if m_type == 'lgb':
        for i in cate_feat:
            data_df[i] = data_df[i].astype('category')
    elif m_type == 'xgb':
        lbl = LabelEncoder()  
        for i in tqdm(cate_feat):
            data_df[i] = lbl.fit_transform(data_df[i].astype(str))
           
    features = num_feat + cate_feat
#     print(len(features), len(set(features)))   
    
    sub,val_pred = get_train_model(data_df, month, m_type)   
    data.loc[(data.mt==month), 'salesVolume'] = sub['forecastVolum'].values
    data.loc[(data.mt==month), 'label'      ] = sub['forecastVolum'].values
    data.loc[(data.mt==(month)), 'pred_label'      ] = sub['forecastVolum'].values
    
    
    
    
    
# sub = data.loc[(data.regMonth>=1)&(data.regYear==2018), ['id','salesVolume']]
# sub.columns = ['id','forecastVolum']
# sub[['id','forecastVolum']].round().astype(int).to_csv('CCF_sales.csv', index=False)

100%|████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  2.07it/s]

all_idx  : 9 20
train_idx: 9 16
valid_idx: 17 17
test_idx : 21 21
Training until validation scores don't improve for 100 rounds.
[100]	training's l2: 128712	valid_1's l2: 98700.9
[200]	training's l2: 41958.5	valid_1's l2: 38841.5
[300]	training's l2: 23711.2	valid_1's l2: 28937.2
[400]	training's l2: 17316.6	valid_1's l2: 26511.4
[500]	training's l2: 13789.8	valid_1's l2: 25838.3
[600]	training's l2: 11344.6	valid_1's l2: 25413.5
[700]	training's l2: 9716.53	valid_1's l2: 25005.3
[800]	training's l2: 8521.85	valid_1's l2: 24786.1
[900]	training's l2: 7601.14	valid_1's l2: 24786.9
[1000]	training's l2: 6807.82	valid_1's l2: 24710.5
[1100]	training's l2: 6154.66	valid_1's l2: 24588.3
[1200]	training's l2: 5603.01	valid_1's l2: 24436.2
[1300]	training's l2: 5128.15	valid_1's l2: 24299.6
[1400]	training's l2: 4756.47	valid_1's l2: 24098.7
[1500]	training's l2: 4411.44	valid_1's l2: 23997.3
[1600]	training's l2: 4081.94	valid_1's l2: 23915.1
[1700]	training's l2: 3801.56	valid_1's l2: 23785.2
[1800]	training's l2: 3551.93	valid_1's l2: 23733.7
[1900]	training's l2: 3322.77	valid_1's l2: 23685.3
[2000]	training's l2: 3105.34	valid_1's l2: 23583.8
Did not meet early stopping. Best iteration is:
[2000]	training's l2: 3105.34	valid_1's l2: 23583.8
0.7973272983520384
valid mean: 497.2429189926641
true  mean: 534.5318181818182
test  mean: 641.6628984132291
(1320, 2)

100%|████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  2.20it/s]

all_idx  : 9 21
train_idx: 9 17
valid_idx: 18 18
test_idx : 22 22
Training until validation scores don't improve for 100 rounds.
[100]	training's l2: 124896	valid_1's l2: 101622
[200]	training's l2: 41221.5	valid_1's l2: 40668.4
[300]	training's l2: 23551.2	valid_1's l2: 30796.4
[400]	training's l2: 17247.5	valid_1's l2: 28629.1
[500]	training's l2: 13644.1	valid_1's l2: 28447.5
[600]	training's l2: 11311.3	valid_1's l2: 28214.8
[700]	training's l2: 9665.8	valid_1's l2: 28306.6
Early stopping, best iteration is:
[602]	training's l2: 11275.5	valid_1's l2: 28202.4
0.7483585609319627
valid mean: 547.3275192104005
true  mean: 523.3159090909091
test  mean: 648.8015280661291
(1320, 2)

100%|████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.75it/s]

all_idx  : 9 22
train_idx: 9 18
valid_idx: 19 19
test_idx : 23 23
Training until validation scores don't improve for 100 rounds.
[100]	training's l2: 121129	valid_1's l2: 101400
[200]	training's l2: 40304.7	valid_1's l2: 38675.6
[300]	training's l2: 23218.8	valid_1's l2: 27340.3
[400]	training's l2: 17179.7	valid_1's l2: 24853.9
[500]	training's l2: 13713.1	valid_1's l2: 23959.2
[600]	training's l2: 11471.2	valid_1's l2: 23400.8
[700]	training's l2: 9962.11	valid_1's l2: 22931.2
[800]	training's l2: 8881.21	valid_1's l2: 22567.1
[900]	training's l2: 8007.93	valid_1's l2: 22383.6
[1000]	training's l2: 7299.37	valid_1's l2: 22289.3
[1100]	training's l2: 6668.06	valid_1's l2: 22270.3
[1200]	training's l2: 6149.12	valid_1's l2: 22150.4
Early stopping, best iteration is:
[1196]	training's l2: 6170.05	valid_1's l2: 22128.1
0.7468931536269028
valid mean: 560.7094271141314
true  mean: 552.2295454545455
test  mean: 734.8046071367794
(1320, 2)

100%|████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  2.18it/s]

all_idx  : 9 23
train_idx: 9 19
valid_idx: 20 20
test_idx : 24 24
Training until validation scores don't improve for 100 rounds.
[100]	training's l2: 118772	valid_1's l2: 145395
[200]	training's l2: 39386.3	valid_1's l2: 51071.7
[300]	training's l2: 22711.1	valid_1's l2: 32006.2
[400]	training's l2: 17040	valid_1's l2: 27020.4
[500]	training's l2: 13774.6	valid_1's l2: 25125.4
[600]	training's l2: 11675.5	valid_1's l2: 24421
[700]	training's l2: 10208	valid_1's l2: 24129.7
[800]	training's l2: 9205.22	valid_1's l2: 23964.6
[900]	training's l2: 8388.5	valid_1's l2: 23799.9
[1000]	training's l2: 7727.56	valid_1's l2: 23768.7
Early stopping, best iteration is:
[989]	training's l2: 7801.96	valid_1's l2: 23734.8
0.7917019686244774
valid mean: 595.4352742803294
true  mean: 620.0212121212121
test  mean: 856.408786058386
(1320, 2)

In [68]:
for month in [21,22,23,24]: 
    m_type = 'lgb' 
    
    data_df, stat_feat = get_stat_feature(data)
    
    num_feat = ['regYear','regMonth','popularity'] + stat_feat
    cate_feat = ['adcode','bodyType','model']
    
    if m_type == 'lgb':
        for i in cate_feat:
            data_df[i] = data_df[i].astype('category')
    elif m_type == 'xgb':
        lbl = LabelEncoder()  
        for i in tqdm(cate_feat):
            data_df[i] = lbl.fit_transform(data_df[i].astype(str))
           
    features = num_feat + cate_feat
#     print(len(features), len(set(features)))   
    
    sub,val_pred = get_train_model(data_df, month, m_type)   
    data.loc[(data.regMonth==(month-24))&(data.regYear==2018), 'salesVolume'] = sub['forecastVolum'].values
    data.loc[(data.regMonth==(month-24))&(data.regYear==2018), 'label'      ] = sub['forecastVolum'].values
#     data.loc[(data.mt==(month)), 'pred_label'      ] = sub['forecastVolum'].values
    
    
    
    
    
sub = data.loc[(data.regMonth>=1)&(data.regYear==2018), ['id','salesVolume']]
sub.columns = ['id','forecastVolum']
# sub[['id','forecastVolum']].round().astype(int).to_csv('CCF_sales.csv', index=False)

100%|████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.37it/s]

all_idx  : 13 24
train_idx: 13 20
valid_idx: 21 21
test_idx : 25 25
Training until validation scores don't improve for 100 rounds.
[100]	training's l2: 86584.9	valid_1's l2: 151719
[200]	training's l2: 27784.3	valid_1's l2: 71704.5
[300]	training's l2: 14902.5	valid_1's l2: 57361.3
[400]	training's l2: 10243.5	valid_1's l2: 52224.7
[500]	training's l2: 7869.38	valid_1's l2: 50304.7
[600]	training's l2: 6385.06	valid_1's l2: 49569.7
[700]	training's l2: 5380.65	valid_1's l2: 48911.9
[800]	training's l2: 4634.41	valid_1's l2: 48274
[900]	training's l2: 4071.47	valid_1's l2: 48026.2
[1000]	training's l2: 3625	valid_1's l2: 47641.9
[1100]	training's l2: 3253.2	valid_1's l2: 47425.4
[1200]	training's l2: 2928.61	valid_1's l2: 47143.3
[1300]	training's l2: 2653.04	valid_1's l2: 46870.8
[1400]	training's l2: 2414.07	valid_1's l2: 46669.9
[1500]	training's l2: 2207.68	valid_1's l2: 46487.6
[1600]	training's l2: 2028.06	valid_1's l2: 46336.7
[1700]	training's l2: 1876.96	valid_1's l2: 46208.4
[1800]	training's l2: 1749.37	valid_1's l2: 46176.2
[1900]	training's l2: 1632.35	valid_1's l2: 46079.2
[2000]	training's l2: 1525.02	valid_1's l2: 46029.5
[2100]	training's l2: 1420.06	valid_1's l2: 45984.2
[2200]	training's l2: 1322.58	valid_1's l2: 45885.2
Early stopping, best iteration is:
[2188]	training's l2: 1333.16	valid_1's l2: 45878
0.7657263463789578

100%|████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.41it/s]

all_idx  : 13 25
train_idx: 13 21
valid_idx: 22 22
test_idx : 26 26
Training until validation scores don't improve for 100 rounds.
[100]	training's l2: 90083.5	valid_1's l2: 118412
[200]	training's l2: 28475.8	valid_1's l2: 59906.1
[300]	training's l2: 15309.6	valid_1's l2: 52080.3
[400]	training's l2: 10785.7	valid_1's l2: 50404.3
[500]	training's l2: 8324.54	valid_1's l2: 49632.1
[600]	training's l2: 6828.3	valid_1's l2: 49046.4
[700]	training's l2: 5813.9	valid_1's l2: 48997.8
Early stopping, best iteration is:
[648]	training's l2: 6301.83	valid_1's l2: 48762.4
0.7352932759641437

100%|████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.40it/s]

all_idx  : 13 26
train_idx: 13 22
valid_idx: 23 23
test_idx : 27 27
Training until validation scores don't improve for 100 rounds.
[100]	training's l2: 93591.6	valid_1's l2: 135289
[200]	training's l2: 29582.9	valid_1's l2: 52574.8
[300]	training's l2: 15864.8	valid_1's l2: 39181.2
[400]	training's l2: 11154.7	valid_1's l2: 36023.5
[500]	training's l2: 8739.67	valid_1's l2: 35331.5
[600]	training's l2: 7173.39	valid_1's l2: 34526.5
[700]	training's l2: 6126.06	valid_1's l2: 34402.5
[800]	training's l2: 5347.97	valid_1's l2: 34349
[900]	training's l2: 4770.82	valid_1's l2: 34426
Early stopping, best iteration is:
[806]	training's l2: 5308.31	valid_1's l2: 34325.1
0.7811424903161602

100%|████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.38it/s]

all_idx  : 13 27
train_idx: 13 23
valid_idx: 24 24
test_idx : 28 28
Training until validation scores don't improve for 100 rounds.
[100]	training's l2: 96023.9	valid_1's l2: 552065
[200]	training's l2: 29709.3	valid_1's l2: 354551
[300]	training's l2: 16067.9	valid_1's l2: 299015
[400]	training's l2: 11490.5	valid_1's l2: 282547
[500]	training's l2: 9067.98	valid_1's l2: 274322
[600]	training's l2: 7522.51	valid_1's l2: 271372
[700]	training's l2: 6477.28	valid_1's l2: 271395
Early stopping, best iteration is:
[658]	training's l2: 6879.88	valid_1's l2: 270441
0.6226761089064834

In [69]:
sub[['id','forecastVolum']].round().astype(int).to_csv('CCF_sales0914.csv', index=False)

In [38]:
for month in [25,26,27,28]: 
    m_type = 'lgb' 
    
    data_df, stat_feat = get_stat_feature(data)
    
    num_feat = ['regYear'] + stat_feat
    cate_feat = ['adcode','bodyType','model','regMonth']
    
    if m_type == 'lgb':
        for i in cate_feat:
            data_df[i] = data_df[i].astype('category')
    elif m_type == 'xgb':
        lbl = LabelEncoder()  
        for i in tqdm(cate_feat):
            data_df[i] = lbl.fit_transform(data_df[i].astype(str))
           
    features = num_feat + cate_feat
    print(len(features), len(set(features)))   
    
    sub,val_pred = get_train_model(data_df, month, m_type)   
    data.loc[(data.regMonth==(month-24))&(data.regYear==2018), 'salesVolume'] = sub['forecastVolum'].values
    data.loc[(data.regMonth==(month-24))&(data.regYear==2018), 'label'      ] = sub['forecastVolum'].values
sub = data.loc[(data.regMonth>=1)&(data.regYear==2018), ['id','salesVolume']]
sub.columns = ['id','forecastVolum']
# sub[['id','forecastVolum']].round().astype(int).to_csv('CCF_sales.csv', index=False)

100%|████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:05<00:00,  1.38s/it]

53 53
all_idx  : 13 24
train_idx: 13 20
valid_idx: 21 21
test_idx : 25 25
Training until validation scores don't improve for 100 rounds.
[100]	training's l2: 7291.26	valid_1's l2: 37932.3
[200]	training's l2: 3715.93	valid_1's l2: 35716.9
[300]	training's l2: 2515.27	valid_1's l2: 35194.8
[400]	training's l2: 1831.38	valid_1's l2: 34788.8
[500]	training's l2: 1397.64	valid_1's l2: 34608.6
[600]	training's l2: 1065.51	valid_1's l2: 34527.1
[700]	training's l2: 849.095	valid_1's l2: 34415.2
[800]	training's l2: 679.238	valid_1's l2: 34333.1
[900]	training's l2: 545.247	valid_1's l2: 34326.4
Early stopping, best iteration is:
[838]	training's l2: 624.086	valid_1's l2: 34316.6
0.7559303097480222
valid mean: 602.8972278482273
true  mean: 649.3121212121212
test  mean: 493.9801201875369

100%|████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:05<00:00,  1.35s/it]

53 53
all_idx  : 13 25
train_idx: 13 21
valid_idx: 22 22
test_idx : 26 26
Training until validation scores don't improve for 100 rounds.
[100]	training's l2: 7936.91	valid_1's l2: 41558.5
Early stopping, best iteration is:
[75]	training's l2: 10761.5	valid_1's l2: 41117.3
0.7414955122487169
valid mean: 623.4500376146684
true  mean: 616.5537878787878
test  mean: 324.6451813135614

100%|████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:05<00:00,  1.36s/it]

53 53
all_idx  : 13 26
train_idx: 13 22
valid_idx: 23 23
test_idx : 27 27
Training until validation scores don't improve for 100 rounds.
[100]	training's l2: 8653.84	valid_1's l2: 32560.4
[200]	training's l2: 4627.91	valid_1's l2: 32133.2
Early stopping, best iteration is:
[155]	training's l2: 5757.15	valid_1's l2: 31853.4
0.7794578141087838
valid mean: 639.6227869473659
true  mean: 673.0143939393939
test  mean: 479.55100257280156

100%|████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:05<00:00,  1.40s/it]

53 53
all_idx  : 13 27
train_idx: 13 23
valid_idx: 24 24
test_idx : 28 28
Training until validation scores don't improve for 100 rounds.
[100]	training's l2: 9306.24	valid_1's l2: 302435
[200]	training's l2: 5107.21	valid_1's l2: 292129
[300]	training's l2: 3583.18	valid_1's l2: 289373
[400]	training's l2: 2709.06	valid_1's l2: 288389
[500]	training's l2: 2162.77	valid_1's l2: 287983
[600]	training's l2: 1746.75	valid_1's l2: 287504
[700]	training's l2: 1446.22	valid_1's l2: 287029
[800]	training's l2: 1196.94	valid_1's l2: 286429
[900]	training's l2: 1008.26	valid_1's l2: 286030
Early stopping, best iteration is:
[856]	training's l2: 1089.91	valid_1's l2: 286004
0.588139278724323
valid mean: 645.3917897243205
true  mean: 899.8204545454546
test  mean: 468.0356962498267